/** Chef workflow owns no Recipe store: edits stay in the existing session draft. */
import {h} from '../../../dom';
import type {PageCtx} from '../../../types';
import {createAttempt,getKnowledgeApi,KnowledgeError,type Adoption,type RecipeDetail,type StandardIngredient,type IngredientRevision,type StandardTechnique,type TechniqueRevision,type Attempt,type Materialization} from '../../../api/knowledge';
import type {AuxiliaryOperation} from '../../../view-models/reload-safety';
import {contractErrorText} from '../../../admin/kit';
import {button,field,input,select,multilingual,section,jsonEvidence,words} from './ui';
import type {Draft} from './model';
type IngredientChoice=StandardIngredient&{id:string;version:number};
type TechniqueChoice=StandardTechnique&{id:string;version:number};
type StandardEditor={kind:'ingredients'|'techniques';id?:string;etag?:string;value:StandardIngredient|StandardTechnique;raw:Record<string,string>;dirty:boolean};
type Operation={kind:'approve'|'freeze'|'ingredients'|'techniques';attempt:Attempt;ticket:AuxiliaryOperation;busy:boolean;unknown:boolean};
interface State {version:number;epoch:number;loading:boolean;adoption?:Adoption;original?:RecipeDetail;error?:unknown;ingredients:IngredientChoice[];techniques:TechniqueChoice[];catalogLoaded:boolean;catalogValid:boolean;catalogLoading:boolean;editor?:StandardEditor;reviewer:string;note:string;sourceConfirmed:boolean;reviewDirty:boolean;operation?:Operation;result?:Materialization}
const states=new WeakMap<Draft,State>();
const title=(value:Record<string,string|undefined>|undefined,lang:string)=>value?.[lang]||value?.zh||value?.en||value?.uk||'';
const recipeDirty=(draft:Draft)=>JSON.stringify(draft.recipe)!==draft.baseline||Object.entries(draft.pending).some(([key,value])=>key!=='assetKind'&&value.trim())||draft.rightsChanged;
export function workflowBlocked(draft:Draft):boolean{return !!draft.workflow?.busy||!!draft.workflow?.unknown;}
function flags(draft:Draft,state:State){draft.workflow={dirty:state.reviewDirty||!!state.editor?.dirty,busy:!!state.operation?.busy,unknown:!!state.operation?.unknown};}
export function workflowPanel(draft:Draft,ctx:PageCtx,current:()=>boolean,paint:()=>void,changed:()=>void):HTMLElement {
 const t=words(ctx.lang),api=getKnowledgeApi();
 let state=states.get(draft);if(!state){state={version:0,epoch:0,loading:false,ingredients:[],techniques:[],catalogLoaded:false,catalogValid:false,catalogLoading:false,reviewer:'',note:'',sourceConfirmed:false,reviewDirty:false};states.set(draft,state);}const s=state;
 const repaint=()=>{flags(draft,s);if(current())(draft.repaint||paint)();};
 const blocked=()=>draft.busy||draft.unknown||workflowBlocked(draft)||!!draft.detail?.archivedAt;
 const changedReview=()=>{s.reviewDirty=true;draft.generation++;flags(draft,s);};
 async function metadata(force=false){
  if(!draft.detail||s.loading)return;const {id,version}=draft.detail;
  if(!force&&s.version===version)return;const epoch=++s.epoch;if(s.version!==version)s.result=undefined;s.version=version;s.loading=true;s.adoption=undefined;s.original=undefined;s.error=undefined;
  try{const {data}=await api.getAdoption(id,version);if(!current()||s.epoch!==epoch||draft.detail?.version!==version)return;
   if(data.recipeId!==id||data.recipeVersion!==version||!data.origin||!data.current)throw new KnowledgeError('Adoption metadata does not match saved Recipe',0,'invalid_source');
   s.adoption=data;const original=await api.request<RecipeDetail>(`/recipes/${id}/revisions/${data.origin.originalRecipeVersion}`);
   if(!current()||s.epoch!==epoch||draft.detail?.version!==version)return;s.original=original.data;
  }catch(error){if(current()&&s.epoch===epoch)s.error=error;}finally{if(s.epoch===epoch){s.loading=false;repaint();}}
 }
 async function catalog(force=false){
  if(s.catalogLoading||(!force&&s.catalogLoaded))return;s.catalogLoading=true;
  try{const list=async<T>(kind:string)=>{const rows:T[]=[];let cursor:string|null=null;const seen=new Set<string>();do{const {data}:{data:{items:T[];nextCursor:string|null}}=await api.request<{items:T[];nextCursor:string|null}>(`/${kind}?limit=100${cursor?'&cursor='+encodeURIComponent(cursor):''}`);if(!Array.isArray(data.items))throw new KnowledgeError('Invalid standard list',0);rows.push(...data.items);cursor=data.nextCursor;if(cursor){if(seen.has(cursor)||seen.size>=100)throw new KnowledgeError('Standard list pagination exceeded its bound',0);seen.add(cursor);}}while(cursor);return rows;};
   const [ingredients,techniques]=await Promise.all([list<IngredientChoice>('ingredients'),list<TechniqueChoice>('techniques')]);if(!current())return;
   // Explicit bindings may be outside the current list search; detail is authoritative.
   const ingredientIds=[...new Set(draft.recipe.ingredients?.map(row=>row.ingredientId).filter((id):id is string=>!!id))];
   const techniqueIds=[...new Set([...(draft.recipe.ingredients?.map(row=>row.kitchenPrep?.techniqueId)||[]),...(draft.recipe.steps?.map(row=>row.techniqueId)||[])].filter((id):id is string=>!!id))];
   const [ingredientDetails,techniqueDetails]=await Promise.all([Promise.all(ingredientIds.map(id=>api.request<IngredientRevision>(`/ingredients/${id}`))),Promise.all(techniqueIds.map(id=>api.request<TechniqueRevision>(`/techniques/${id}`)))]);
   if(!current())return;for(const {data}of ingredientDetails){const i=ingredients.findIndex(row=>row.id===data.id),row={id:data.id,version:data.version,...data.ingredient};if(i<0)ingredients.push(row);else ingredients[i]=row;}
   for(const {data}of techniqueDetails){const i=techniques.findIndex(row=>row.id===data.id),row={id:data.id,version:data.version,...data.technique};if(i<0)techniques.push(row);else techniques[i]=row;}
   s.ingredients=ingredients;s.techniques=techniques;s.catalogLoaded=true;s.catalogValid=true;
  }catch(error){if(current()){s.error=error;s.catalogLoaded=true;s.catalogValid=false;}}finally{s.catalogLoading=false;repaint();}
 }
 async function write(kind:Operation['kind'],attempt?:Attempt){
  if(!current()||draft.busy||draft.unknown||s.operation?.busy||draft.detail?.archivedAt)return;
  if(!s.operation){if(!attempt)return;s.operation={kind,attempt,ticket:draft.registration.beginOperation('write'),busy:false,unknown:false};}
  const operation=s.operation;operation.busy=true;s.error=undefined;repaint();
  try{const reply=await api.send<unknown>(operation.attempt);if(operation.kind==='freeze'){const data=reply.data as Materialization;if(data.recipeId!==draft.detail?.id||data.recipeVersion!==draft.detail.version||typeof data.dishRef!=='string'||!/^kb[a-z0-9-]+$/.test(data.dishRef))throw new KnowledgeError('Fixed result does not match the requested Recipe',0,'invalid_source');}draft.registration.settleOperation(operation.ticket,'completed');if(!current())return;
   s.operation=undefined;
   if(operation.kind==='approve'){s.reviewDirty=false;s.reviewer='';s.note='';s.sourceConfirmed=false;await metadata(true);}
   else if(operation.kind==='freeze'){const data=reply.data as Materialization;s.result=data;}
   else{s.editor=undefined;await catalog(true);}
  }catch(error){if(!current()){draft.registration.settleOperation(operation.ticket,'failed');return;}s.error=error;
   if(error instanceof KnowledgeError&&error.uncertain){s.operation=operation;operation.unknown=true;draft.registration.markUnknown(operation.ticket);}
   else{draft.registration.settleOperation(operation.ticket,'failed');s.operation=undefined;}
  }finally{operation.busy=false;repaint();}
 }
 async function editStandard(kind:StandardEditor['kind'],id?:string){
  if(blocked()||s.editor?.dirty)return;
  try{let value:StandardEditor['value']=kind==='ingredients'?{name:{}}:{kind:'cut',name:{}};let etag:string|undefined;
   if(id){const reply=await api.request<IngredientRevision|TechniqueRevision>(`/${kind}/${id}`);if(!current())return;value='ingredient'in reply.data?reply.data.ingredient:reply.data.technique;etag=reply.etag||undefined;}
   s.editor={kind,id,etag,value:structuredClone(value),raw:{},dirty:false};s.error=undefined;repaint();
  }catch(error){if(current()){s.error=error;repaint();}}
 }
 const panel=section(t('原方与厨房修订','Original and kitchen revision','Оригінал і кухонна редакція'));
 panel.setAttribute('data-testid','recipe-adoption');
 if(!draft.detail){panel.append(h('p',{},t('先保存原方，再补充厨房资料并核定。未知用量可以保留。','Save the original first, then add kitchen information and approve. Unknown amounts can stay unknown.','Спочатку збережіть оригінал, потім додайте кухонні дані й затвердьте. Невідомі кількості можна залишити.')));return panel;}
 if(s.version!==draft.detail.version&&!s.loading)void metadata();
 if(!s.catalogLoaded&&!s.catalogLoading)void catalog();
 const saved=draft.detail;
 panel.append(h('p',{},s.adoption?`${t('来源','Origin','Походження')}: ${s.adoption.origin.kind==='favorite'?t('收藏候选','Favorite candidate','Кандидат з обраного'):s.adoption.origin.kind==='legacy'?t('旧资料导入','Legacy import','Імпорт старих даних'):t('手工原方','Manual original','Ручний оригінал')} · ${t('原方','Original','Оригінал')} v${s.adoption.origin.originalRecipeVersion} · ${t('厨房保存版本','Saved kitchen version','Збережена кухонна версія')} v${saved.version}`:t('正在读取核定与原方…','Reading approval and original…','Завантаження затвердження й оригіналу…')));
 function fulltext(detail:RecipeDetail):HTMLElement {const r=detail.recipe;return h('article',{'class':'kb-comparison-column'},h('h4',{},`${title(r.title,ctx.lang)} · v${detail.version}`),h('p',{},title(r.description,ctx.lang)),h('p',{},r.baseServings===undefined?t('基础份数未知','Base servings unknown','Базові порції невідомі'):`${t('基础份数','Base servings','Базові порції')}: ${r.baseServings}`),h('ol',{},...(r.ingredients||[]).map(row=>h('li',{},h('strong',{},title(row.name,ctx.lang)),h('p',{},row.amount.kind==='exact'?`${row.amount.value} ${row.amount.unit}`:row.amount.raw||t('用量未知','Amount unknown','Кількість невідома')),row.amount.kind==='exact'&&row.amount.raw?h('p',{},row.amount.raw):null,row.rawText?h('p',{},row.rawText):null,row.preparation?h('p',{},title(row.preparation,ctx.lang)):null,row.kitchenPrep?jsonEvidence(row.kitchenPrep,t('厨房切配资料','Kitchen preparation','Кухонна підготовка')):null))),h('ol',{},...(r.steps||[]).map(row=>h('li',{},h('p',{},title(row.text,ctx.lang))))),...(detail.sourceRecords||detail.sources||[]).map(source=>jsonEvidence(source,t('完整原始来源','Complete original source','Повне оригінальне джерело'))));}
 if(s.original)panel.append(h('details',{'class':'kb-comparison'},h('summary',{},t('展开完整原方与已保存厨房修订','Compare complete original and saved kitchen revision','Порівняти повний оригінал і збережену кухонну редакцію')),h('div',{'class':'kb-comparison-grid'},fulltext(s.original),fulltext(saved))));
 if(s.error){const error=s.error;panel.append(h('p',{role:'alert'},error instanceof KnowledgeError?(contractErrorText(error.code,ctx.lang)||t('操作未完成，输入已保留。','Request failed; input is preserved.','Запит не виконано; дані збережено.')):t('操作未完成，输入已保留。','Request failed; input is preserved.','Запит не виконано; дані збережено.')),jsonEvidence(error instanceof KnowledgeError?{status:error.status,code:error.code,message:error.message,details:error.details,key:s.operation?.attempt.key}:{message:String(error)},t('技术支持详情','Support details','Деталі для підтримки')));}
 const retry=button(t('重新核对原方与标准资料','Refresh original and standards','Оновити оригінал і стандарти'),()=>{void metadata(true);void catalog(true);});retry.disabled=blocked()||s.loading||s.catalogLoading;panel.append(retry);
 if(s.operation?.unknown){const verify=button(t('核对操作结果（使用同一请求）','Verify operation result (same request)','Перевірити результат (той самий запит)'),()=>void write(s.operation!.kind),true);verify.disabled=s.operation.busy;panel.append(h('p',{role:'status'},t('结果尚未确认。请保留输入，核对原请求的结果。','The result is unconfirmed. Keep input and verify the original request.','Результат не підтверджено. Збережіть дані та перевірте початковий запит.')),verify);}
 const approval=s.adoption?.kitchenApproval;
 if(approval){panel.append(h('p',{role:'status'},`${t('此保存版本已由厨房核定','This saved version is approved by the kitchen','Цю збережену версію затверджено кухнею')} · ${approval.reviewer} · ${approval.createdAt}`),h('p',{},approval.note),jsonEvidence(approval.dependencies,t('固定的标准资料版本','Pinned standard versions','Зафіксовані версії стандартів')));
  const freeze=button(t('采用此版本到菜单','Use this version in a menu','Використати цю версію в меню'),()=>void write('freeze',api.materializationAttempt(saved.id,saved.version)),true);freeze.disabled=blocked()||!!recipeDirty(draft)||!s.adoption||s.adoption.current.archived;panel.append(freeze);
 }else{
  const confirmed=h('input',{type:'checkbox','data-testid':'source-confirmed'});confirmed.checked=s.sourceConfirmed;confirmed.addEventListener('change',()=>{s.sourceConfirmed=confirmed.checked;changedReview();});
  const form=h('fieldset',{disabled:blocked(),'class':'kb-form'},field(t('核定师傅','Approving chef','Шеф, що затверджує'),input(s.reviewer,value=>{s.reviewer=value;changedReview();})),field(t('核定说明（未知项与厨房调整）','Approval note (unknowns and kitchen changes)','Примітка затвердження (невідоме й зміни)'),input(s.note,value=>{s.note=value;changedReview();},true)),h('label',{},confirmed,t('已完整核对原方来源与厨房修订，未知项保留','I reviewed the complete original and kitchen revision; unknowns are preserved','Я перевірив повний оригінал і кухонну редакцію; невідоме збережено')));
  const approve=button(t('核定已保存版本','Approve saved version','Затвердити збережену версію'),()=>{
   if(!s.reviewer.trim()||!s.note.trim()||!s.sourceConfirmed){s.error=new KnowledgeError('Reviewer, note and source confirmation are required',400,'INVALID_APPROVAL');repaint();return;}
   if(recipeDirty(draft)||!draft.etag||!s.catalogValid||!s.adoption)return;
   const ids=[...new Set(saved.recipe.ingredients?.map(row=>row.ingredientId).filter((id):id is string=>!!id))],techIds=[...new Set([...(saved.recipe.ingredients?.map(row=>row.kitchenPrep?.techniqueId)||[]),...(saved.recipe.steps?.map(row=>row.techniqueId)||[])].filter((id):id is string=>!!id))];
   const ingredientVersions:Record<string,number>={},techniqueVersions:Record<string,number>={};for(const id of ids){const row=s.ingredients.find(row=>row.id===id);if(!row){s.error=new KnowledgeError('Ingredient binding is unavailable',422,'INVALID_INGREDIENT_BINDINGS');repaint();return;}ingredientVersions[id]=row.version;}for(const id of techIds){const row=s.techniques.find(row=>row.id===id);if(!row){s.error=new KnowledgeError('Technique binding is unavailable',422,'INVALID_TECHNIQUE_BINDINGS');repaint();return;}techniqueVersions[id]=row.version;}
   void write('approve',api.approvalAttempt(saved.id,saved.version,{reviewer:s.reviewer,note:s.note,sourceConfirmed:s.sourceConfirmed,ingredientVersions,techniqueVersions},draft.etag));
  },true);approve.disabled=blocked()||!!recipeDirty(draft)||!s.adoption||!s.catalogValid||s.adoption.current.archived;form.append(approve);panel.append(form,h('p',{},t('先保存厨房修订，再核定该版本。无量调料和未绑定材料不会阻止手工使用。','Save kitchen edits before approving that version. Unknown amounts and unbound materials allow manual use.','Збережіть кухонні зміни перед затвердженням версії. Невідомі кількості й неприв’язані матеріали дозволяють ручне використання.')));
 }
 if(s.result){const result=s.result;panel.append(h('p',{role:'status'},`${t('已固定菜谱版本','Recipe version fixed','Версію рецепта зафіксовано')} v${result.recipeVersion}`),h('a',{href:`#/dish/${result.dishRef}`},t('查看固定菜品','View fixed dish','Переглянути зафіксовану страву')));
  const next=button(t('继续选择菜单日期与份数','Choose menu dates and servings','Вибрати дати меню й порції'),()=>{if(!current())return;const planId=ctx.planId;if(planId){ctx.planSelection?.select(planId);location.hash=`#/admin/plan/${encodeURIComponent(planId)}/select/${encodeURIComponent(result.dishRef)}`;}else location.hash='#/admin/plan';},true);panel.append(h('p',{},ctx.planId?`${t('当前计划','Selected plan','Вибраний план')}: ${ctx.planId}`:t('先选择菜单计划，再添加菜品。','Select a menu plan before adding the dish.','Виберіть план меню перед додаванням страви.')),next);
 }
 // Entry points are here; row bindings below reuse this same explicit identity inventory.
 const standards=section(t('标准材料与技法','Standard ingredients and techniques','Стандартні інгредієнти й техніки'),h('p',{},t('相同名称不会自动合并。明确选择共享材料 ID；空白单位、净料率和采购规格表示未知。修改标准资料会生成新版本，已核定版本保持原样。','Matching names are independent. Explicitly bind a shared ingredient ID. Blank units, yield and purchase specifications mean unknown. Standard edits create a new version; approvals stay fixed.','Однакові назви незалежні. Явно прив’яжіть спільний ID інгредієнта. Порожні одиниці, вихід і закупівельні параметри означають невідоме. Зміни створюють нову версію; затвердження незмінні.')));
 for(const [kind,text]of [['ingredients',t('标准材料','Standard ingredient','Стандартний інгредієнт')],['techniques',t('标准技法','Standard technique','Стандартна техніка')]]as const){const add=button(`＋ ${text}`,()=>void editStandard(kind));add.disabled=blocked()||!!s.editor;standards.append(add);const rows=kind==='ingredients'?s.ingredients:s.techniques;const chooser=select('',[['',t('选择已有资料编辑','Choose existing standard to edit','Вибрати стандарт для редагування')],...rows.map(row=>[row.id,`${title(row.name,ctx.lang)} · v${row.version} · ${row.id.slice(0,8)}`]as[string,string])],id=>{if(id)void editStandard(kind,id);});chooser.disabled=blocked()||!!s.editor;standards.append(field(text,chooser));}
 if(s.editor)standards.append(standardForm(s.editor));panel.append(standards);flags(draft,s);return panel;
 function standardForm(editor:StandardEditor):HTMLElement {
  const value=editor.value;const changedStandard=()=>{editor.dirty=true;draft.generation++;flags(draft,s);};
  const form=h('fieldset',{disabled:blocked(),'class':'kb-form','data-testid':'standard-editor'},h('legend',{},editor.id?t('编辑标准资料（新版本）','Edit standard (new version)','Редагувати стандарт (нова версія)'):t('新建标准资料','Create standard','Створити стандарт')),multilingual(t('标准名称','Standard name','Назва стандарту'),value.name,name=>{value.name=name;changedStandard();}));
  const scalar=(key:string,label:string,initial:string)=>field(label,input(editor.raw[key]??initial,text=>{editor.raw[key]=text;changedStandard();}));
  if(editor.kind==='techniques'){const technique=value as StandardTechnique;form.append(field(t('技法类型','Technique type','Тип техніки'),select(technique.kind,[['cut',t('切配','Cut','Нарізання')],['heat',t('加热','Heat','Нагрівання')],['pretreat',t('预处理','Pretreat','Попередня обробка')]],kind=>{technique.kind=kind as StandardTechnique['kind'];changedStandard();})),multilingual(t('技法说明','Technique notes','Примітки техніки'),technique.note,note=>{if(Object.keys(note).length)technique.note=note;else delete technique.note;changedStandard();},true));}
  else{const ingredient=value as StandardIngredient;form.append(field(t('基准单位（留空为未知）','Base unit (blank is unknown)','Базова одиниця (порожньо — невідомо)'),select(ingredient.baseUnit||'',[['',t('未知','Unknown','Невідомо')],['g','g'],['ml','ml'],['pcs','pcs']],unit=>{if(unit)ingredient.baseUnit=unit as StandardIngredient['baseUnit'];else delete ingredient.baseUnit;changedStandard();})),field(t('材料类型','Ingredient role','Роль інгредієнта'),select(ingredient.role||'',[['',t('未知','Unknown','Невідомо')],['main',t('主料','Main','Основний')],['seasoning',t('调料','Seasoning','Приправа')]],role=>{if(role)ingredient.role=role as StandardIngredient['role'];else delete ingredient.role;changedStandard();})),scalar('yield',t('净料率（0–1，未知留空；pcs 不设）','Yield (0–1, blank unknown; omit for pcs)','Вихід (0–1, невідоме порожнє; не для pcs)'),ingredient.yield===undefined?'':String(ingredient.yield)),scalar('pcsToGram',t('每个克数（未知留空）','Grams per piece (blank unknown)','Грами на штуку (невідоме порожнє)'),ingredient.pcsToGram===undefined?'':String(ingredient.pcsToGram)),scalar('supplier',t('供应商（未知留空）','Supplier (blank unknown)','Постачальник (невідоме порожнє)'),ingredient.purchase?.supplier||''),scalar('packSize',t('每包装净含量','Quantity per package','Кількість в упаковці'),ingredient.purchase?.packSize===undefined?'':String(ingredient.purchase.packSize)),field(t('包装单位','Package unit','Одиниця упаковки'),select(editor.raw.packUnit??ingredient.purchase?.packUnit??'',[['',t('未知','Unknown','Невідомо')],...['g','kg','ml','l','pcs','pack','tbsp','tsp','pinch','to-taste'].map(unit=>[unit,unit]as[string,string])],unit=>{editor.raw.packUnit=unit;changedStandard();})),scalar('minPacks',t('最小包装数（可留空）','Minimum packages (optional)','Мінімум упаковок (необов’язково)'),ingredient.purchase?.minPacks===undefined?'':String(ingredient.purchase.minPacks)),scalar('price',t('参考价格（未知留空）','Reference price (blank unknown)','Довідкова ціна (невідоме порожнє)'),ingredient.purchase?.lastPrice===undefined?'':String(ingredient.purchase.lastPrice.amount)),field(t('币种','Currency','Валюта'),select(editor.raw.currency??ingredient.purchase?.lastPrice?.currency??'',[['',t('未知','Unknown','Невідомо')],...['CNY','USD','UAH','EUR'].map(unit=>[unit,unit]as[string,string])],unit=>{editor.raw.currency=unit;changedStandard();})));const stock=h('input',{type:'checkbox'});stock.checked=!!ingredient.trackStock;stock.addEventListener('change',()=>{ingredient.trackStock=stock.checked;changedStandard();});form.append(h('label',{},stock,t('记录现有量','Track on hand','Облік залишку')),scalar('onHand',t('现有量（基准单位，未知留空）','On hand (base unit, blank unknown)','Залишок (базова одиниця, невідоме порожнє)'),ingredient.onHand===undefined?'':String(ingredient.onHand)));}
  const save=button(t('保存标准资料新版本','Save standard version','Зберегти версію стандарту'),()=>{
   try{let body=structuredClone(value);if(editor.kind==='ingredients'){const ingredient=body as StandardIngredient;const number=(key:string,original:number|undefined)=>{const raw=editor.raw[key];if(raw===undefined)return original;if(!raw.trim())return undefined;const parsed=Number(raw);if(!Number.isFinite(parsed))throw new KnowledgeError('Invalid numeric standard field: '+key,400,'INVALID_INGREDIENT');return parsed;};for(const key of ['yield','pcsToGram','onHand']as const){const n=number(key,ingredient[key]);if(n===undefined)delete ingredient[key];else ingredient[key]=n;}
    const supplier=(editor.raw.supplier??ingredient.purchase?.supplier??'').trim(),packSize=number('packSize',ingredient.purchase?.packSize),packUnit=editor.raw.packUnit??ingredient.purchase?.packUnit??'',minPacks=number('minPacks',ingredient.purchase?.minPacks),price=number('price',ingredient.purchase?.lastPrice?.amount),currency=editor.raw.currency??ingredient.purchase?.lastPrice?.currency;
    if(supplier||packSize!==undefined||packUnit||minPacks!==undefined||price!==undefined||currency){if(!supplier||packSize===undefined||!packUnit)throw new KnowledgeError('Complete supplier, package size and unit or leave all unknown',400,'INVALID_INGREDIENT');if((price===undefined)!==!currency)throw new KnowledgeError('Reference price needs both amount and currency, or both unknown',400,'INVALID_INGREDIENT');ingredient.purchase={supplier,packSize,packUnit,...(minPacks===undefined?{}:{minPacks}),...(price===undefined?{}:{lastPrice:{amount:price,currency:currency as 'CNY'}})};}else delete ingredient.purchase;
   }if(editor.id&&!editor.etag)throw new KnowledgeError('Read the current standard before editing',428,'PRECONDITION_REQUIRED');void write(editor.kind,createAttempt(`/${editor.kind}${editor.id?'/'+editor.id:''}`,editor.id?'PUT':'POST',body,editor.etag));
   }catch(error){s.error=error;repaint();}
  },true);save.disabled=blocked();const close=button(t('关闭标准资料编辑','Close standard editor','Закрити редактор стандарту'),()=>{if(editor.dirty&&!window.confirm(t('放弃这份标准资料输入？','Discard this standard input?','Відкинути введені дані стандарту?')))return;s.editor=undefined;repaint();});close.disabled=blocked();form.append(save,close);return form;
 }
}
/** Explicit row selection; names are labels and never establish shared identity. */
export function kitchenFields(draft:Draft,ctx:PageCtx,changed:()=>void,ingredientIndex?:number,stepIndex?:number):HTMLElement {
 const s=states.get(draft),t=words(ctx.lang),row=ingredientIndex===undefined?undefined:draft.recipe.ingredients?.[ingredientIndex],step=stepIndex===undefined?undefined:draft.recipe.steps?.[stepIndex];
 const update=()=>{draft.recipe.recipeFormatVersion='2';changed();};
 const fields=h('div',{class:'kb-kitchen-fields'});
 const technique=(value:string|undefined,change:(id:string)=>void)=>field(t('标准技法（明确选择）','Standard technique (explicit choice)','Стандартна техніка (явний вибір)'),select(value||'',[['',t('未指定 / 未知','Unspecified / unknown','Не визначено / невідомо')],...(s?.techniques||[]).map(item=>[item.id,`${title(item.name,ctx.lang)} · v${item.version} · ${item.id.slice(0,8)}`]as[string,string]),...(value&&!s?.techniques.some(item=>item.id===value)?[[value,t('已绑定，资料待读取','Bound; standard loading','Прив’язано; стандарт завантажується')]as[string,string]]:[])],change));
 if(row){fields.append(field(t('共享标准材料（明确绑定 ID）','Shared standard ingredient (explicit ID binding)','Спільний стандартний інгредієнт (явна прив’язка ID)'),select(row.ingredientId||'',[['',t('未绑定，单独手工判断','Unbound, separate manual decision','Без прив’язки, окреме ручне рішення')],...(s?.ingredients||[]).map(item=>[item.id,`${title(item.name,ctx.lang)} · v${item.version} · ${item.id.slice(0,8)}`]as[string,string]),...(row.ingredientId&&!s?.ingredients.some(item=>item.id===row.ingredientId)?[[row.ingredientId,t('已绑定，资料待读取','Bound; standard loading','Прив’язано; стандарт завантажується')]as[string,string]]:[])],id=>{if(id)row.ingredientId=id;else delete row.ingredientId;update();})));const prep=()=>row.kitchenPrep??={};const prune=()=>{if(row.kitchenPrep&&!Object.keys(row.kitchenPrep).length)delete row.kitchenPrep;update();};fields.append(technique(row.kitchenPrep?.techniqueId,id=>{if(id)prep().techniqueId=id;else if(row.kitchenPrep)delete row.kitchenPrep.techniqueId;prune();}),field(t('厨房准备时机','Kitchen preparation timing','Час кухонної підготовки'),select(row.kitchenPrep?.timing||'',[['',t('未知','Unknown','Невідомо')],['day-before',t('前一天准备','Day before','Напередодні')],['morning',t('当天上午准备','Morning','Вранці')],['before-service',t('餐前准备','Before service','До подачі')]],timing=>{if(timing)prep().timing=timing as 'day-before'|'morning'|'before-service';else if(row.kitchenPrep)delete row.kitchenPrep.timing;prune();})),field(t('厨房切配尺寸（未知留空）','Kitchen cut size (blank unknown)','Розмір нарізання (невідоме порожнє)'),input(row.kitchenPrep?.size||'',size=>{if(size.trim())prep().size=size;else if(row.kitchenPrep)delete row.kitchenPrep.size;prune();})),multilingual(t('厨房准备补充说明','Kitchen preparation notes','Примітки кухонної підготовки'),row.kitchenPrep?.note,note=>{if(Object.keys(note).length)prep().note=note;else if(row.kitchenPrep)delete row.kitchenPrep.note;prune();},true));}
 if(step)fields.append(technique(step.techniqueId,id=>{if(id)step.techniqueId=id;else delete step.techniqueId;update();}));return fields;
}
