// Reviewer-only instrumentation. Actual main.ts and actual page singleton renderers remain unchanged.
import {inspectReloadSafety} from '../src/view-models/reload-safety';
import {setLang} from '../src/i18n';
import {clearToken} from '../src/admin/token';
const A='a'.repeat(40),B='b'.repeat(40),origin='https://application-api.local.invalid';
const clone=x=>structuredClone(x),checks=[],ledger=[],gates=[];
const boot=Number(sessionStorage.getItem('review-boots')||0)+1;sessionStorage.setItem('review-boots',String(boot));
const prior=sessionStorage.getItem('review-evidence');
const salt={schemaVersion:'2',name:{zh:'盐',en:'Salt',uk:'Сіль'},baseUnit:'g',trackStock:false};
const soup={schemaVersion:'3',name:{zh:'原汤',en:'Soup',uk:'Суп'},status:'draft',components:[{ingredientRef:'salt'}],steps:[]};
const seed={schemaVersion:'3',name:{zh:'原计划',en:'Original plan'},meals:[{date:'2026-09-14',mealType:'lunch',dishRef:'soup',plannedServings:8}]};
const savedMock=JSON.parse(sessionStorage.getItem('review-mock-backend')||'null');const sources=new Map(savedMock?.sources||[]),history=new Map(savedMock?.history||[]);let serial=savedMock?.serial||0,holdReads=false,holdWrite=false,loseWrite=false,holdTranslation=false,holdProgress=false,holdClipboard=false,failPlan=false,failManifest=new URLSearchParams(location.search).has('failmanifest');
let runId=10,runCompleted=true,translationGate;
const nativeFetch=globalThis.fetch.bind(globalThis);
const json=(x,status=200)=>Response.json(x,{status});
const failure=(status,code)=>json({ok:false,errors:[{path:'',code,message:code}]},status);
function defer(kind,path){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});const gate={kind,path,resolve,reject,promise,ended:false};gates.push(gate);return gate;}
function source(kind,id,revision){const key=`${kind}/${id}`;if(revision&&history.has(`${key}/${revision}`))return clone(history.get(`${key}/${revision}`));if(sources.has(key))return clone(sources.get(key));if(kind==='shopping-list'||id==='new')return null;return{content:clone(kind==='plan'?seed:kind==='dish'?soup:salt),commit:revision||A,blobSha:`${kind}-${id}-original`};}
function store(kind,id,body){const s={content:clone(body),commit:(++serial).toString(16).padStart(40,'0'),blobSha:`saved-${serial}`};sources.set(`${kind}/${id}`,s);history.set(`${kind}/${id}/${s.commit}`,s);sessionStorage.setItem('review-mock-backend',JSON.stringify({serial,sources:[...sources],history:[...history]}));return s;}
const changes=()=>({onlineCommit:A,lastPublishedAt:'2026-09-10T00:00:00Z',unpublished:[{sha:B,at:'2026-09-11T00:00:00Z',role:'chef',endpoint:'POST /plan/week-41',subject:'Local fixture',files:['data/menu-plans/week-41.json']}],publishes:[{sha:A,at:'2026-09-10T00:00:00Z',runId:10,isOnline:true}]});
globalThis.fetch=async(url,init={})=>{const u=new URL(String(url),location.href),method=init.method||'GET';
 if(u.origin!==origin){if(u.pathname.endsWith('/data/build.json')){ledger.push({method,path:u.pathname,probe:u.searchParams.has('__publication')});if(failManifest){failManifest=false;return failure(503,'unavailable');}}return nativeFetch(url,init);}
 ledger.push({method,path:u.pathname,revision:u.searchParams.get('revision'),ifMatch:new Headers(init.headers).get('If-Match'),ifNoneMatch:new Headers(init.headers).get('If-None-Match')});
 if(method==='GET'&&holdReads)await defer('read',u.pathname).promise;
 if(method==='GET'){
  if(u.pathname==='/catalog')return json({ok:true,commit:u.searchParams.get('revision')||A,dishes:{soup},ingredients:{salt},techniques:[],suppliers:[],translations:{machine:0,human:0,stale:0}});
  if(u.pathname==='/changes')return json({ok:true,...changes()});
  if(u.pathname.startsWith('/publish/')){if(holdProgress)await defer('progress',u.pathname).promise;return json({ok:true,runId:Number(u.pathname.split('/').at(-1)),status:runCompleted?'success':'in_progress',steps:[],failedStep:null,failureReason:null,unmappedSteps:[],runCompleted,runConclusion:runCompleted?'success':null});}
  const m=u.pathname.match(/^\/source\/([^/]+)\/([^/]+)$/);if(m){if(failPlan&&m[1]==='plan')return failure(503,'unavailable');const s=source(m[1],m[2],u.searchParams.get('revision'));return s?json({ok:true,...s}):failure(404,'not_found');}
 }
 if(method==='POST'){
  if(u.pathname==='/translate'){if(holdTranslation){translationGate=defer('translation',u.pathname);await translationGate.promise;}return json({ok:true,translations:{en:'Translated salt',uk:'Переклад'}});}
  if(u.pathname==='/publish')return json({ok:true,runId:++runId,mode:'dispatch'});
  if(u.pathname.startsWith('/rollback/')){if(holdWrite)await defer('write',u.pathname).promise;return json({ok:true,commit:B,restoredFrom:u.pathname.split('/').at(-1),changedFiles:1});}
  const m=u.pathname.match(/^\/(plan|dish|ingredient|shopping-list)\/([^/]+)(?:\/draft)?$/);if(m){const s=store(m[1],m[2],JSON.parse(init.body));if(holdWrite)await defer('write',u.pathname).promise;if(loseWrite){loseWrite=false;throw new TypeError('Simulated lost ACK');}return json({ok:true,commit:s.commit,blobSha:s.blobSha,unchanged:false,warnings:[]});}
 }
 throw new Error(`Unexpected simulated request ${method} ${u.pathname}`);
};
Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{if(holdClipboard)await defer('clipboard','local-clipboard').promise;}}});
if(!sessionStorage.getItem('canteenos.token'))sessionStorage.setItem('canteenos.token','A'.repeat(43));
setLang('en');if(!location.hash)location.hash='#/admin';
const panel=document.createElement('aside');panel.id='review-panel';panel.innerHTML='<strong>INDEPENDENT LOCAL TEST · real application/main/PWA · simulated API only</strong><div id="review-controls"></div><pre id="review-output"></pre>';
panel.style.cssText='background:#fff1c9;padding:12px;border:2px solid #876b27';document.body.prepend(panel);
const out=panel.querySelector('pre'),controls=panel.querySelector('div');out.style.cssText='white-space:pre-wrap;overflow-wrap:anywhere;max-height:280px;overflow:auto';
const pause=(ms=35)=>new Promise(r=>setTimeout(r,ms));
const $=s=>document.querySelector('#app')?.querySelector(s);
const assert=(v,m)=>{if(!v)throw Error(m);};
async function wait(fn,label,ms=7000){const end=Date.now()+ms;while(Date.now()<end){if(fn())return;await pause();}throw Error('Timed out: '+label);}
function state(){return inspectReloadSafety();}
const extraState={};function paint(extra={}){Object.assign(extraState,extra);out.textContent=JSON.stringify({head:import.meta.env.VITE_REVIEW_HEAD_SHA||'3eb2f351755b73122b26f2a2cee5a523dee49aaa',boot,summary:`${checks.filter(x=>x.pass).length}/${checks.length}`,checks,route:location.hash,safety:state(),controller:!!navigator.serviceWorker.controller,pending:gates.filter(g=>!g.ended).map(g=>({kind:g.kind,path:g.path})),ledger,viewText:document.querySelector('#app')?.textContent,inputs:[...document.querySelectorAll('#app input, #app textarea')].map(e=>({id:e.id,focus:e.dataset.focus,value:e.value})),...extraState},null,2);sessionStorage.setItem('review-evidence',out.textContent);}
function check(name,pass,detail){checks.push({name,pass:!!pass,detail});paint();assert(pass,name);}
function edit(selector,value,type='input'){const el=$(selector);assert(el,'Missing input '+selector);el.value=value;el.dispatchEvent(new Event(type,{bubbles:true}));}
function click(selector){const el=$(selector);assert(el,'Missing '+selector);assert(!el.disabled,'Disabled '+selector);el.click();}
function textButton(text){const el=[...document.querySelectorAll('#app button')].find(e=>e.textContent.trim()===text);assert(el,'Missing button '+text);assert(!el.disabled,'Disabled '+text);el.click();}
async function route(path,selector){location.hash='#/'+path;await pause();if(selector)await wait(()=>$(selector),'route '+path);}
async function language(lang,selector){setLang(lang);await pause();if(selector)await wait(()=>$(selector),'language '+lang);}
async function login(path='admin',selector='.adm-home'){clearToken();sessionStorage.setItem('canteenos.token','B'.repeat(43));await route('admin/not-a-screen','.adm-notfound');await route(path,selector);}
function release(gate,fail=false){gate.ended=true;fail?gate.reject(new Error('Explicit local read failure')):gate.resolve();}
function add(label,work){const b=document.createElement('button');b.textContent=label;b.style.cssText='min-height:44px;margin:4px';b.onclick=async()=>{b.disabled=true;try{await work();paint();}catch(error){checks.push({name:label,pass:false,error:String(error.stack||error)});paint();}finally{b.disabled=false;}};controls.append(b);}
add('1 Run actual application matrix',async()=>{
 await wait(()=>$('.adm-home'),'initial Home');await wait(()=>state().reason==='clear','initial Home reads');
 check('actual main Home ready with no untracked residue',state().reason==='clear');
 holdReads=true;await login();await wait(()=>gates.filter(g=>g.kind==='read'&&!g.ended).length===3,'three Home reads');check('actual Home registers all three reads before await',state().reason==='saving');
 const readCount=ledger.length;await language('zh','.adm-home');check('language redraw reuses Home reads',ledger.length===readCount&&state().reason==='saving');
 await route('admin/plan/private-old');await wait(()=>gates.filter(g=>!g.ended).length>=4,'old Plan Source');holdReads=false;await login();await wait(()=>$('.adm-home').textContent.includes('1'),'new Home ready');
 check('old Home and Plan reads survive auth without old identity disclosure',state().reason==='unknown'&&!JSON.stringify(state()).includes('private-old'));
 const newHome=$('.adm-home');const old=gates.filter(g=>!g.ended);release(old[0],true);await pause();check('one old read cannot release its siblings',state().reason==='unknown');for(const g of old.slice(1))release(g);await wait(()=>state().reason==='clear','old read settlement');check('late old initializations preserve new Home DOM and clear own coverage',newHome===$('.adm-home')&&state().reason==='clear');
 await language('en','.adm-home');failPlan=true;await route('admin/plan/read-fails');await wait(()=>$('[role="alert"]'),'Plan read failure');check('failed real Plan initialization is readable and ends protection',state().reason==='clear'&&!$('[data-focus="servings-0"]'));failPlan=false;await route('admin/not-a-screen','.adm-notfound');check('actual dispatcher unknown route is read-only',state().reason==='clear');
 await route('admin/plan/week-41','[data-focus="servings-0"]');edit('[data-focus="servings-0"]','1.5');await route('admin/plan/week-41/import','#adm-import-text');check('offscreen invalid Plan raw blocks globally',state().reason==='dirty');edit('#adm-import-text','private unparsed import');await route('admin/dish/soup','.adm-dish-form');edit('[data-pointer="/name"] input','本地汤');await route('admin/ingredient/salt','#adm-ing-name-zh');edit('#adm-ing-name-zh','本地盐');await route('purchase/new/week-41','[data-focus="new-list-id"]');edit('[data-focus="new-list-id"]','private-shopping-raw');
 await route('admin/publish','.adm-pub-publish');await wait(()=>!$('.adm-pub-publish').disabled,'Publish ready');const dirty=state();check('all five offscreen actual editor raw owners coexist',dirty.reason==='dirty'&&['plan','dish','ingredient','shopping-list'].every(kind=>dirty.records.some(r=>r.kind===kind&&r.dirty))&&dirty.records.some(r=>r.kind==='import'&&r.dirty),dirty.records.filter(r=>r.dirty).map(r=>({kind:r.kind,id:r.id})));
 await route('admin/plan/week-41','[data-focus="servings-0"]');await language('uk','[data-focus="servings-0"]');check('Plan raw survives real route and language', $('[data-focus="servings-0"]').value==='1.5');await route('admin/plan/week-41/import','#adm-import-text');check('Import raw survives real route and language',$('#adm-import-text').value==='private unparsed import');await route('admin/dish/soup','.adm-dish-form');check('Dish raw survives real route and language',$('[data-pointer="/name"] input').value==='本地汤');await route('admin/ingredient/salt','#adm-ing-name-zh');check('Ingredient raw survives real route and language',$('#adm-ing-name-zh').value==='本地盐');await route('purchase/new/week-41','[data-focus="new-list-id"]');check('Purchase raw survives real route and language',$('[data-focus="new-list-id"]').value==='private-shopping-raw');
 await language('en','[data-focus="new-list-id"]');await login();await wait(()=>state().reason==='clear','fresh session');
 await route('admin/plan/save-flow','[data-focus="servings-0"]');edit('[data-focus="servings-0"]','9');holdWrite=true;click('.tm-actions button');await wait(()=>gates.some(g=>g.kind==='write'&&!g.ended),'Plan save sent');edit('[data-focus="servings-0"]','10');await route('admin','.adm-home');check('actual C1 save stays pending offscreen with later raw',state().reason==='saving');loseWrite=true;holdWrite=false;release(gates.find(g=>g.kind==='write'&&!g.ended));await wait(()=>state().reason==='unknown','lost save ACK');const beforeVerify=ledger.filter(c=>c.method==='POST').length;await route('admin/plan/save-flow','[data-focus="servings-0"]');check('unknown Plan returns with later input and no repost',$('[data-focus="servings-0"]').value==='10'&&ledger.filter(c=>c.method==='POST').length===beforeVerify);textButton('Verify save outcome');await wait(()=>state().reason==='dirty','Plan verification');check('two forced Source reads confirm ACK while later edits stay dirty',ledger.filter(c=>c.path==='/source/plan/save-flow').length===3&&$('[data-focus="servings-0"]').value==='10');click('.tm-actions button');await wait(()=>state().reason==='clear','Plan later save');
 await route('admin/ingredient/salt','#adm-ing-name-zh');holdTranslation=true;click('.adm-ing-translate');await wait(()=>translationGate,'translation dispatched');await route('admin','.adm-home');check('actual Ingredient auxiliary read is protected offscreen',state().reason==='saving');await route('admin/ingredient/salt','#adm-ing-name-zh');await language('uk','#adm-ing-name-zh');holdTranslation=false;release(translationGate);await wait(()=>state().reason==='dirty','translation ends');check('translation settles original ticket into retained dirty draft',state().reason==='dirty');
 await language('en','#adm-ing-name-zh');await login();await wait(()=>state().reason==='clear','new session after translation');await route('admin/publish','.adm-pub-publish');holdProgress=true;runCompleted=false;click('.adm-pub-publish');await wait(()=>gates.some(g=>g.kind==='progress'&&!g.ended),'publish polling');await route('admin','.adm-home');check('accepted Publish remains protected offscreen until proven terminal',state().reason==='saving');runCompleted=true;holdProgress=false;release(gates.find(g=>g.kind==='progress'&&!g.ended));await wait(()=>state().reason==='clear','matching Publish terminal');check('known same-run completion clears actual Publish owner',!ledger.some(c=>c.path==='/publish/latest'));
 await route('purchase/new/week-41','[data-focus="new-list-id"]');edit('[data-focus="new-list-id"]','integration-shop');textButton('Read latest saved plans');await wait(()=>$('.tm-slot input'),'shopping scope');textButton('Create list to check');await wait(()=>$('.tm-material'),'shopping created');check('actual main C2 creates all-check list before any persistence',$('.tm-decisions button').getAttribute('aria-pressed')==='true'&&$('.tm-decisions button').disabled);
 holdWrite=true;textButton('Save list');await wait(()=>gates.some(g=>g.kind==='write'&&!g.ended),'shopping write');await route('admin','.adm-home');check('actual Purchase C1 save protects application offscreen',state().reason==='saving');holdWrite=false;release(gates.find(g=>g.kind==='write'&&!g.ended));await wait(()=>state().reason==='clear','shopping ACK');await route('purchase/integration-shop','.tm-material');check('manual decisions unlock only after actual C1 ACK',!$('.tm-decisions button').disabled);holdClipboard=true;textButton('Copy list');textButton('Copy list');await route('admin','.adm-home');const copies=gates.filter(g=>g.kind==='clipboard'&&!g.ended);check('two actual Purchase clipboard writes remain separate offscreen',copies.length===2&&state().reason==='saving');release(copies[0]);await pause();check('one clipboard completion does not settle sibling',state().reason==='saving');holdClipboard=false;release(copies[1],true);await wait(()=>state().reason==='clear','clipboard failure settles');
 await route('admin/dish/soup','.adm-dish-form');holdTranslation=true;translationGate=null;click('.adm-dish-translate');await wait(()=>translationGate,'Dish translation');await route('admin','.adm-home');check('actual Dish auxiliary translation remains protected offscreen',state().reason==='saving');await login('admin/dish/soup','.adm-dish-form');check('old Dish read is anonymous under actual auth switch',state().reason==='unknown');holdTranslation=false;release(translationGate);await wait(()=>state().reason==='clear','old Dish read ended');check('late old Dish translation cannot fill current raw',$('[data-pointer="/name/en"] input').value==='Soup');
 await route('admin/plan/sw-plan','[data-focus="servings-0"]');edit('[data-focus="servings-0"]','11');check('SW phase starts with actual Plan dirty draft',state().reason==='dirty');
});
add('Fail next manifest refresh',()=>{failManifest=true;});
add('Startup publication failure check',async()=>{await wait(()=>$('.adm-home'),'Home despite unavailable publication');await wait(()=>state().reason==='clear','Home reads');check('publication read failure does not prevent actual Home or leave untracked coverage',state().reason==='clear');await route('admin/plan/startup-failure','[data-focus="servings-0"]');check('Plan works after failed publication with its own Source/catalog',state().reason==='clear');await route('purchase/new/week-41','[data-focus="new-list-id"]');check('Purchase works with explicit plan after failed publication',state().reason==='clear');});
add('Inspect live state',()=>paint({priorBootEvidence:prior?JSON.parse(prior):null}));
add('2 Request real SW check',async()=>{const reg=await navigator.serviceWorker.getRegistration();assert(reg,'actual generated SW registration');await reg.update();await wait(()=>reg.waiting,'waiting SW',15000);check('new generated service worker waits without reload or activation',!!reg.waiting&&boot===Number(sessionStorage.getItem('review-boots')));});
add('3 Verify dirty update dialog',async()=>{click('.update-bar button');await wait(()=>$('dialog'),'update dialog');const d=$('dialog');check('actual update dialog lists offscreen/visible dirty Plan and explicit choice',d.textContent.includes('sw-plan')&&d.querySelectorAll('button').length===2);d.querySelector('button').click();});
let trackedInput,refreshes=0;navigator.serviceWorker.addEventListener('controllerchange',()=>refreshes++);
add('4 External activation preserves editor',async()=>{trackedInput=$('[data-focus="servings-0"]');const before=ledger.filter(c=>c.probe).length;const reg=await navigator.serviceWorker.getRegistration();assert(reg?.waiting,'waiting worker');reg.waiting.postMessage({type:'SKIP_WAITING'});await wait(()=>ledger.filter(c=>c.probe).length>before,'main fresh publication read');await pause(200);check('actual controller change refreshes reader without replacing editing DOM',trackedInput===$('[data-focus="servings-0"]')&&trackedInput.value==='11'&&boot===Number(sessionStorage.getItem('review-boots')),{refreshes});});
add('5 Start held save and verify update block',async()=>{holdWrite=true;click('.tm-actions button');await wait(()=>gates.some(g=>g.kind==='write'&&!g.ended),'held C1');await route('admin','.adm-home');click('.update-bar button');await wait(()=>$('dialog'),'saving dialog');check('actual offscreen pending save blocks update without discard',$('dialog').querySelectorAll('button').length===1&&state().reason==='saving');$('dialog button').click();});
add('6 Lose ACK and verify unknown update block',async()=>{holdWrite=false;loseWrite=true;release(gates.find(g=>g.kind==='write'&&!g.ended));await wait(()=>state().reason==='unknown','unknown');click('.update-bar button');await wait(()=>$('dialog'),'unknown dialog');check('actual offscreen unknown blocks update without discard',$('dialog').querySelectorAll('button').length===1&&state().reason==='unknown');$('dialog button').click();});
add('7 Reconcile and request confirmed clean update',async()=>{await route('admin/plan/sw-plan','[data-focus="servings-0"]');textButton('Verify save outcome');await wait(()=>state().reason==='clear','reconciled clean');check('only exact read evidence clears real C1 unknown',state().reason==='clear');armNativeIntent('clean-after-source-reconciliation');paint();click('.update-bar button');});
add('8 Old auth save remains anonymous',async()=>{await login('admin/plan/secret-old-plan','[data-focus="servings-0"]');await wait(()=>state().reason==='clear','fresh old auth');edit('[data-focus="servings-0"]','12');holdWrite=true;click('.tm-actions button');await wait(()=>gates.some(g=>g.kind==='write'&&!g.ended),'old write');holdWrite=false;await login('admin/plan/new-session-plan','[data-focus="servings-0"]');edit('[data-focus="servings-0"]','13');release(gates.find(g=>g.kind==='write'&&!g.ended));await pause(100);check('real transport hidden old ACK retains anonymous previous-session save',state().reason==='unknown'&&state().records.some(r=>r.id==='previous-session-save')&&!JSON.stringify(state()).includes('secret-old-plan'));click('.update-bar button');await wait(()=>$('dialog'),'old auth dialog');check('old auth update prompt discloses no private ID and offers no discard',$('dialog').querySelectorAll('button').length===1&&!$('dialog').textContent.includes('secret-old-plan')&&$('[data-focus="servings-0"]').value==='13');$('dialog button').click();});

paint();
add('Minimal retired Ingredient unload control',async()=>{
 await wait(()=>$('.adm-home'),'actual Home');await wait(()=>state().reason==='clear','Home clear');
 const observeUnload=()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return{defaultPrevented:event.defaultPrevented,returnValue:event.returnValue};};
 const clean=observeUnload();check('minimal clean actual Home control does not cancel beforeunload',!clean.defaultPrevented,clean);
 await route('admin/ingredient/salt','#adm-ing-name-zh');edit('#adm-ing-name-zh','OLD RETIRED LOCAL RAW');check('minimal actual Ingredient raw enters dirty registry',state().reason==='dirty');
 await login();await wait(()=>state().reason==='clear','retired raw is no active work');check('auth retires pure local Ingredient raw from shared registry',state().reason==='clear');
 const retired=observeUnload();checks.push({name:'retired local Ingredient raw must not cancel a clean current-session unload',pass:!retired.defaultPrevented,detail:retired});
 const reg=await navigator.serviceWorker.getRegistration();paint({unloadDiagnostic:{clean,retired},nativeSW:reg?{waiting:reg.waiting?.state,installing:reg.installing?.state,active:reg.active?.state,controller:navigator.serviceWorker.controller?.state}:null});
});
add('Minimal Plan dirty setup',async()=>{await wait(()=>$('.adm-home'),'Home');await wait(()=>state().reason==='clear','Home clear');await route('admin/plan/sw-plan','[data-focus="servings-0"]');edit('[data-focus="servings-0"]','11');check('control only actual Plan is dirty',state().reason==='dirty');});
add('Inspect native service worker',async()=>{const reg=await navigator.serviceWorker.getRegistration();paint({nativeSW:reg?{waiting:reg.waiting?.state,installing:reg.installing?.state,active:reg.active?.state,controller:navigator.serviceWorker.controller?.state}:null});});

// R2 follow-up: prove an actual new JS lifetime, not just a clean registry snapshot.
function armNativeIntent(caseName){
 const intent={caseName,beforeBoot:boot,beforeEvidence:JSON.parse(out.textContent),expectedAfterBoot:boot+1,at:Date.now()};
 sessionStorage.setItem('review-native-intent',JSON.stringify(intent));
 setTimeout(()=>{if(Number(sessionStorage.getItem('review-boots'))===boot){checks.push({name:'actual native reload completes after user consent',pass:false,caseName,detail:{expected:boot+1,actual:boot}});paint({nativeIntent:intent,nativeReloadFailure:true});}},4500);
}
const nativeIntent=JSON.parse(sessionStorage.getItem('review-native-intent')||'null');
if(nativeIntent){
 checks.push({name:'new application JS lifetime follows exactly one user-authorized reload',pass:boot===nativeIntent.expectedAfterBoot,detail:{beforeBoot:nativeIntent.beforeBoot,actualBoot:boot,caseName:nativeIntent.caseName}});
 setTimeout(()=>{checks.push({name:'native reload remains exactly once after the update settles',pass:Number(sessionStorage.getItem('review-boots'))===nativeIntent.expectedAfterBoot,detail:{expected:nativeIntent.expectedAfterBoot,actual:Number(sessionStorage.getItem('review-boots'))}});paint({nativeIntent,nativeReloadStable:true});},4000);
 paint({nativeIntent});
}
add('Prepare Import raw discard case',async()=>{await wait(()=>$('.adm-home'),'Home');await wait(()=>state().reason==='clear','Home reads');await route('admin/plan/raw-discard/import','#adm-import-text');edit('#adm-import-text','unapplied raw must require consent');check('actual Import raw is dirty before any update',state().reason==='dirty');});
add('Prepare Ingredient raw discard case',async()=>{await wait(()=>$('.adm-home'),'Home');await wait(()=>state().reason==='clear','Home reads');await route('admin/ingredient/salt','#adm-ing-name-zh');edit('#adm-ing-name-zh','未保存食材');check('actual Ingredient raw is dirty before any update',state().reason==='dirty');});
add('Prepare Dish raw discard case',async()=>{await wait(()=>$('.adm-home'),'Home');await wait(()=>state().reason==='clear','Home reads');await route('admin/dish/soup','.adm-dish-form');edit('[data-pointer="/name"] input','未保存菜谱');check('actual Dish raw is dirty before any update',state().reason==='dirty');});
add('Confirm production dirty-discard update',async()=>{
 assert(state().reason==='dirty','real dirty state required');const records=state().records.filter(r=>r.dirty).map(r=>({kind:r.kind,id:r.id}));
 click('.update-bar button');await wait(()=>$('dialog'),'production discard prompt');const dialog=$('dialog');check('actual update requires one explicit discard decision',dialog.querySelectorAll('button').length===2&&records.some(r=>dialog.textContent.includes(r.id)),records);
 armNativeIntent('explicit-dirty-discard:'+records.map(r=>r.kind).join(','));paint();dialog.querySelectorAll('button')[1].click();
});
add('Confirm production clean update',async()=>{assert(state().reason==='clear','clear evidence required');armNativeIntent('clean-control');paint();click('.update-bar button');});
add('Check pending or unknown cannot reach native reload',async()=>{
 const reason=state().reason;assert(['saving','unknown'].includes(reason),'pending or unknown required');click('.update-bar button');await wait(()=>$('dialog'),'blocking prompt');const dialog=$('dialog');check('pending or unknown permits no discard/update override',dialog.querySelectorAll('button').length===1&&Number(sessionStorage.getItem('review-boots'))===boot,{reason,boot});dialog.querySelector('button').click();
});

add('Check real team navigation and plan auth',async()=>{
 await wait(()=>$('.adm-home'),'actual Home');await wait(()=>state().reason==='clear','Home complete');
 const expected={en:['Meals','For the team','Plan meals'],zh:['用餐安排','团队查看','排每天的菜'],uk:['Харчування','Для команди','Планування меню']};
 for(const lang of ['en','zh','uk']){
  await language(lang,'.adm-home');click('.corner');const drawer=$('#drawer'),menu=drawer.querySelector('a[href="#/menu"]'),plan=drawer.querySelector('a[href="#/admin/plan/week-41"]');
  check('actual team drawer removes guest semantics in '+lang,expected[lang].slice(0,2).every(x=>menu?.textContent.includes(x))&&!/guest|顾客|гостей/.test(drawer.textContent));
  check('actual verified first plan is a live route in '+lang,!!plan&&plan.textContent.includes(expected[lang][2]));click('.corner');
 }
 await language('en','.adm-home');click('.corner');$('#drawer a[href="#/admin/plan/week-41"]').click();await wait(()=>$('[data-focus="servings-0"]'),'actual authenticated Plan');check('actual shell link opens production Plan with existing auth',location.hash==='#/admin/plan/week-41'&&$('#drawer').hidden);
 clearToken();await route('admin/not-a-screen','.adm-lock');const before=ledger.filter(x=>x.method==='GET'&&!x.path.includes('/data/')).length;click('.corner');$('#drawer a[href="#/admin/plan/week-41"]').click();await wait(()=>$('.adm-lock'),'plan auth lock');check('same real plan route does not bypass authentication',$('.adm-lock')&&ledger.filter(x=>x.method==='GET'&&!x.path.includes('/data/')).length===before);
 await login('admin/plan/week-41','[data-focus="servings-0"]');edit('[data-focus="servings-0"]','11');
});
add('Check failed publication clears old plan target',async()=>{click('.corner');const drawer=$('#drawer');check('actual failed reader removes stale editable plan link',!drawer.querySelector('a[href^="#/admin/plan/"]')&&!/guest|顾客|гостей/.test(drawer.textContent)&&!!drawer.querySelector('[aria-disabled="true"]'));click('.corner');});
add('Check empty team publication has no invented plan target',async()=>{click('.corner');const drawer=$('#drawer');check('actual empty team publication keeps team role but no plan link',drawer.textContent.includes('For the team')&&drawer.textContent.includes('No plan available')&&!drawer.querySelector('a[href^="#/admin/plan/"]'));click('.corner');});
add('Check restored legacy publication retains its own navigation',async()=>{click('.corner');const drawer=$('#drawer');check('actual legacy publication retains guest wording only under legacy target',drawer.textContent.includes('for guests')&&!!drawer.querySelector('a[href="#/admin/plan/week-41"]'));click('.corner');});

add('Check actual public journey with offscreen raw',async()=>{
 await wait(()=>$('.adm-home'),'Home');await wait(()=>state().reason==='clear','Home clear');
 await route('admin/plan/public-guard','[data-focus="servings-0"]');edit('[data-focus="servings-0"]','1.5');const before=ledger.filter(x=>!x.path.includes('/data/')).length;
 await route('menu','[data-frozen-menu]');const revision=$('[data-frozen-menu]').dataset.sourceRevision;
 check('actual main Menu uses frozen published revision while Plan raw stays protected',!!revision&&state().reason==='dirty');
 click('[data-recipe-link]');await wait(()=>$('.dsheet [data-frozen-prep]'),'real recipe overlay');const recipe=$('.dsheet [data-frozen-prep]');
 check('real Menu recipe retains all five components and three steps',recipe.querySelectorAll('[data-component-index]').length===5&&recipe.querySelectorAll('[data-step-index]').length===3);
 check('real full recipe keeps 7500 g original quantity with no planned-serving multiplication',recipe.querySelector('[data-original-quantity]').textContent.replace(/[\s,\u00a0\u202f]/g,'')==='7500g',recipe.querySelector('[data-original-quantity]').textContent);
 click('.dsheet [data-component-index="0"] a[href^="#/prep/"]');await wait(()=>!$('.dsheet')&&$('[data-frozen-prep]'),'real material Prep');
 for(const lang of ['en','zh','uk']){await language(lang,'[data-frozen-prep]');check('actual Prep preserves revision original quantity and offscreen raw in '+lang,$('[data-frozen-prep]').dataset.sourceRevision===revision&&$('[data-original-quantity]').textContent.replace(/[\s,\u00a0\u202f]/g,'')==='7500g'&&state().reason==='dirty');}
 await wait(()=>$('figure[data-asset-state="available"] img'),'same-revision asset');const img=$('figure[data-asset-state="available"] img');img.scrollIntoView();await wait(()=>img.complete&&img.naturalWidth>0,'actual image decoding');check('actual public image bytes decode without private API fallback',ledger.filter(x=>!x.path.includes('/data/')).length===before&&img.naturalWidth===2,{revision,naturalWidth:img.naturalWidth});
 await language('en','[data-frozen-prep]');await route('admin/plan/public-guard','[data-focus="servings-0"]');check('public navigation returns to retained invalid Plan input',$('[data-focus="servings-0"]').value==='1.5');edit('[data-focus="servings-0"]','8');await route('admin','.adm-home');
});
add('Check Plan preview to Purchase continuity',async()=>{
 await route('admin/plan/continuity','[data-focus="servings-0"]');edit('[data-focus="servings-0"]','');textButton('Preview ingredients');await wait(()=>$('[data-preview="draft"]'),'C2 local preview');check('actual Plan supports no servings and previews recorded ingredient',!!$('[data-preview="draft"]')&&$('[data-preview="draft"]').textContent.includes('Salt')&&state().reason==='dirty');
 click('a[href="#/purchase/new/continuity"]');await wait(()=>$('[data-focus="new-list-id"]'),'real Plan shopping link');edit('[data-focus="new-list-id"]','continuity-shop');textButton('Read latest saved plans');await wait(()=>$('.tm-slot input'),'saved shopping scope');textButton('Create list to check');await wait(()=>$('.tm-material'),'all-check shopping');check('actual Plan link reaches C2 all-check Purchase with editing Plan retained',state().reason==='dirty'&&$('.tm-decisions button').disabled&&$('.tm-decisions button').getAttribute('aria-pressed')==='true');await route('admin/plan/continuity','[data-focus="servings-0"]');check('Purchase return retains no-servings Plan raw',$('[data-focus="servings-0"]').value==='');
});
