/**
 * 发布：POST /publish（契约 §1.4 / §5）与 GET /publish/:runId（§1.5 / §4.2–§4.4）。
 *
 * runId 的认领办法由 PR #67 定死（ADR-0007 跟进事项 1）：dispatch API 返回 204 不带 runId，
 * 调用方传 request_id，workflow 的 run-name 回显成 `publish · <request_id>`，
 * worker 轮询 runs 列表**按名字精准匹配**认领。**不要按时间戳取最新一条** ——
 * build-deploy.yml 有 concurrency: group: pages，publish 会排队，两次挨得近就会认错人。
 */
import type { Ctx } from "../context.js";
import { githubClient } from "../context.js";
import type { GitHubClient, WorkflowJob, WorkflowRun } from "../github.js";
import { commitMessage } from "../github.js";
import { fail } from "../http.js";

export type StageKey = "validate" | "translate" | "build" | "deploy";
export type StepState = "pending" | "in_progress" | "success" | "failure" | "skipped";

/**
 * 四步映射（契约 §4.2 / ADR-0007 §6），步骤名**逐字**取自 main 上的 build-deploy.yml。
 * 这张表是硬耦合：改 workflow 的步骤名会静默打断进度显示，所以下面还有 unmappedSteps 兆底。
 */
export const STAGE_STEPS: Record<StageKey, readonly string[]> = {
  validate: [
    "Validate data/**/*.json against schemas/*.schema.json",
    "Gate — build-data --check --compare-snapshots",
  ],
  translate: [
    "Machine-translate missing en/uk (only when DEEPL_API_KEY is set)",
    "Commit machine translations back to main",
  ],
  build: [
    "Build @canteenos/core",
    "Build data (three sheets + build.json → packages/web/public/data/)",
    "Build web (vite → packages/web/dist/)",
  ],
  deploy: [],
};

export const STAGE_LABELS: Record<StageKey, string> = {
  validate: "检查数据",
  translate: "补翻译",
  build: "生成三张单",
  deploy: "上线",
};

export const STAGE_ORDER: StageKey[] = ["validate", "translate", "build", "deploy"];

/** ④ 上线 = build 作业里的 upload-pages-artifact 步骤 + deploy 作业整体（契约 §4.2）。 */
const DEPLOY_STEP_MARK = "upload-pages-artifact";
const DEPLOY_JOB_MARK = "deploy-pages";

/**
 * D-13：自动生成的步骤（`Set up job` / `Run actions/checkout@v4` / `Post Run …` / `Complete job`）
 * 不可能被映射，按前缀与固定名单忽略。
 *
 * 外加一条**契约漏掉的**：build-deploy.yml 里还有一个带显式 name 的步骤
 * "Install workspace dependencies"，§4.2 的表里没有它。照 D-13 字面实现的话，
 * 每一次真实发布都会 status: "unmapped" —— 见交付说明里的契约缺陷清单。
 */
const IGNORED_EXPLICIT_STEPS = new Set<string>([
  "Set up job",
  "Complete job",
  "Checkout",
  "Set up runner",
  "Post job cleanup",
  "Install workspace dependencies",
]);

function isAutoGenerated(name: string): boolean {
  return name.startsWith("Run ") || name.startsWith("Post ") || IGNORED_EXPLICIT_STEPS.has(name);
}

interface Entry {
  name: string;
  status: string | null;
  conclusion: string | null;
  startedAt: string | null;
  completedAt: string | null;
}

export interface PublishStep {
  key: StageKey;
  label: string;
  state: StepState;
  startedAt: string | null;
  completedAt: string | null;
}

export interface PublishProgress {
  ok: true;
  runId: number | null;
  status: "queued" | "in_progress" | "success" | "failure" | "timeout" | "unmapped";
  htmlUrl: string;
  steps: PublishStep[];
  failedStep: string | null;
  failureReason: string | null;
  unmappedSteps: string[];
  slow?: boolean;
}

const SLOW_STEP_MS = 10 * 60 * 1000;
const RUN_TIMEOUT_MS = 20 * 60 * 1000;

function aggregate(entries: Entry[]): {
  state: StepState;
  startedAt: string | null;
  completedAt: string | null;
  firstFailure: string | null;
} {
  if (entries.length === 0) {
    return { state: "pending", startedAt: null, completedAt: null, firstFailure: null };
  }
  const failure = entries.find((e) => e.conclusion === "failure" || e.conclusion === "timed_out");
  const started = entries.map((e) => e.startedAt).filter((v): v is string => Boolean(v)).sort();
  const completed = entries.map((e) => e.completedAt).filter((v): v is string => Boolean(v)).sort();
  const allCompleted = entries.every((e) => e.status === "completed");

  let state: StepState;
  if (failure) state = "failure";
  else if (allCompleted && entries.every((e) => e.conclusion === "skipped")) state = "skipped";
  else if (allCompleted && entries.every((e) => e.conclusion === "success" || e.conclusion === "skipped"))
    state = "success";
  else if (entries.every((e) => e.status === "queued" || e.status === null || e.status === "pending"))
    state = "pending";
  else state = "in_progress";

  return {
    state,
    startedAt: started[0] ?? null,
    completedAt: allCompleted ? (completed[completed.length - 1] ?? null) : null,
    firstFailure: failure?.name ?? null,
  };
}

/** run + jobs → 契约 §1.5 的响应体（D-03 的形状）。 */
export function mapProgress(run: WorkflowRun, jobs: WorkflowJob[], now: number): PublishProgress {
  const byStage: Record<StageKey, Entry[]> = {
    validate: [],
    translate: [],
    build: [],
    deploy: [],
  };
  const unmappedSteps: string[] = [];

  for (const job of jobs) {
    const isDeployJob = job.steps.some((s) => s.name.includes(DEPLOY_JOB_MARK));
    if (isDeployJob) {
      byStage.deploy.push({
        name: job.name,
        status: job.status,
        conclusion: job.conclusion,
        startedAt: job.startedAt,
        completedAt: job.completedAt,
      });
    }
    for (const step of job.steps) {
      const entry: Entry = {
        name: step.name,
        status: step.status,
        conclusion: step.conclusion,
        startedAt: step.startedAt,
        completedAt: step.completedAt,
      };
      const stage = STAGE_ORDER.find((key) => STAGE_STEPS[key].includes(step.name));
      if (stage) {
        byStage[stage].push(entry);
        continue;
      }
      if (step.name.includes(DEPLOY_STEP_MARK)) {
        byStage.deploy.push(entry);
        continue;
      }
      if (isDeployJob || isAutoGenerated(step.name)) continue;
      unmappedSteps.push(step.name);
    }
  }

  const steps: PublishStep[] = [];
  let failedStep: string | null = null;
  let failureReason: string | null = null;
  for (const key of STAGE_ORDER) {
    const agg = aggregate(byStage[key]);
    steps.push({
      key,
      label: STAGE_LABELS[key],
      state: agg.state,
      startedAt: agg.startedAt,
      completedAt: agg.completedAt,
    });
    if (agg.state === "failure" && failedStep === null) {
      failedStep = key;
      failureReason = agg.firstFailure;
    }
  }

  const runCompleted = run.status === "completed";
  const startedMs = Date.parse(run.runStartedAt ?? run.createdAt);
  const elapsed = Number.isNaN(startedMs) ? 0 : now - startedMs;
  const slow = !runCompleted && steps.some((s) => s.state === "in_progress") && elapsed > SLOW_STEP_MS;

  let status: PublishProgress["status"];
  if (failedStep !== null) status = "failure";
  else if (unmappedSteps.length > 0) status = "unmapped";
  else if (runCompleted) status = run.conclusion === "success" ? "success" : "failure";
  else if (elapsed > RUN_TIMEOUT_MS) status = "timeout";
  else if (run.status === "queued" || steps.every((s) => s.state === "pending")) status = "queued";
  else status = "in_progress";

  const progress: PublishProgress = {
    ok: true,
    runId: run.id,
    status,
    htmlUrl: run.htmlUrl,
    steps,
    failedStep,
    failureReason,
    unmappedSteps,
  };
  if (slow) progress.slow = true;
  return progress;
}

export async function handlePublishStatus(ctx: Ctx): Promise<unknown> {
  const raw = ctx.params.runId ?? "";
  if (!/^[1-9][0-9]*$/.test(raw)) throw fail("bad_id", { message: "发布编号不对" });
  const runId = Number(raw);
  const gh = githubClient(ctx);
  const run = await gh.getRun(runId);
  if (!run) throw fail("not_found");
  const jobs = await gh.listRunJobs(runId);
  return mapProgress(run, jobs, ctx.rt.now());
}

/**
 * D-17 顺带建议的只读别名：dispatch 之后 90 秒没认领到 runId 时（T-28），
 * 前端拿不到编号，只能靠这个补上最近一次 dispatch run。
 */
export async function handlePublishLatest(ctx: Ctx): Promise<unknown> {
  const gh = githubClient(ctx);
  const workflow = ctx.env.PUBLISH_WORKFLOW ?? "build-deploy.yml";
  const runs = await gh.listRuns(workflow, `?branch=${encodeURIComponent(gh.branch)}&per_page=1`);
  const run = runs[0];
  if (!run) throw fail("not_found");
  const jobs = await gh.listRunJobs(run.id);
  return mapProgress(run, jobs, ctx.rt.now());
}

const CLAIM_INTERVAL_MS = 2000;

function claimTimeoutMs(ctx: Ctx): number {
  const raw = Number(ctx.env.PUBLISH_CLAIM_TIMEOUT_MS ?? "90000");
  return Number.isFinite(raw) && raw >= 0 ? raw : 90000;
}

async function claimRun(
  ctx: Ctx,
  gh: GitHubClient,
  workflow: string,
  query: string,
  match: (run: WorkflowRun) => boolean,
): Promise<number | null> {
  const deadline = ctx.rt.now() + claimTimeoutMs(ctx);
  for (;;) {
    const runs = await gh.listRuns(workflow, query);
    const hit = runs.find(match);
    if (hit) return hit.id;
    if (ctx.rt.now() >= deadline) return null;
    await ctx.rt.sleep(CLAIM_INTERVAL_MS);
  }
}

export async function handlePublish(ctx: Ctx): Promise<unknown> {
  const mode = (ctx.env.PUBLISH_MODE ?? "dispatch").trim();
  if (mode === "off") throw fail("dispatch_unavailable");
  if (mode !== "dispatch" && mode !== "push-trigger") {
    throw fail("not_configured", { message: `PUBLISH_MODE 配成了 ${mode}，只认 dispatch / push-trigger / off` });
  }

  const gh = githubClient(ctx);
  const workflow = ctx.env.PUBLISH_WORKFLOW ?? "build-deploy.yml";

  if (mode === "dispatch") {
    const requestId = ctx.rt.requestId();
    await gh.dispatchWorkflow(workflow, gh.branch, { request_id: requestId });
    const runName = `publish · ${requestId}`;
    const runId = await claimRun(
      ctx,
      gh,
      workflow,
      `?event=workflow_dispatch&branch=${encodeURIComponent(gh.branch)}&per_page=20`,
      (run) => run.name === runName,
    );
    return { ok: true, runId, mode: "dispatch", requestId };
  }

  // 降级 D1（契约 §5.2）：造一个**不带 [skip ci]** 的空 commit，靠 push: branches: [main] 触发构建。
  const head = await gh.getHeadSha();
  const base = await gh.getCommit(head);
  const commit = await gh.createCommit(
    commitMessage("chore(publish): 触发构建", ctx.role, ctx.endpointConcrete),
    base.treeSha,
    [head],
  );
  if (!(await gh.updateRef(commit))) throw fail("conflict");

  const runId = await claimRun(
    ctx,
    gh,
    workflow,
    `?branch=${encodeURIComponent(gh.branch)}&per_page=20`,
    (run) => run.headSha === commit,
  );
  return { ok: true, runId, mode: "push-trigger", commit };
}
