import assert from 'node:assert/strict';
import { readFile, mkdtemp, writeFile, rm } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { test, after } from 'node:test';
const here = dirname(fileURLToPath(import.meta.url)), require = createRequire(import.meta.url);
const esbuild = await import(pathToFileURL(createRequire(require.resolve('vite/package.json')).resolve('esbuild')));
const dir = await mkdtemp(join(tmpdir(), 'team-ingredient-'));after(() => rm(dir, { recursive: true, force: true }));
const entry = join(here, '../src/pages/admin/ingredient-new.ts');
const injected = {
  '../../api/client': 'export const getApi = () => globalThis.__ingredientHarness.getLegacy();',
  '../../api/team-meals': 'export const getTeamMealsApi = () => globalThis.__ingredientHarness.team;',
  '../admin': 'export const adminHref = (...parts) => "#/admin" + (parts.length ? "/" + parts.map(encodeURIComponent).join("/") : "");',
};
const source = await readFile(process.env.INGREDIENT_SOURCE ?? entry, 'utf8');
const bundle = await esbuild.build({
  stdin: { contents: source + `\nexport {createTeamMealsApi} from ${JSON.stringify(join(here,'../src/api/team-meals.ts'))};\nexport {HttpAdminApi} from ${JSON.stringify(join(here,'../src/api/client.ts'))};\nexport {ApiError} from ${JSON.stringify(join(here,'../src/api/types.ts'))};\nexport {clearToken as changeAuth} from ${JSON.stringify(join(here,'../src/admin/token.ts'))};\nexport const probeDraft = () => typeof ingredientOwners === 'undefined' ? draft : [...ingredientOwners.values()].find(r => r.key === 'salt' && r.api.sessionKey() === r.session)?.draft;\n`, resolveDir: dirname(entry), loader: 'ts' },
  plugins: [{name:'ingredient-seams',setup(build){build.onResolve({filter:/^\.\.\//},a=>injected[a.path] && (a.importer==='<stdin>' || a.importer.endsWith('ingredient-new.ts')) ? {path:a.path,namespace:'ingredient-test'}:undefined);build.onLoad({filter:/.*/,namespace:'ingredient-test'},a=>({contents:injected[a.path],loader:'js'}));}}],
  bundle:true,write:false,format:'esm',platform:'browser',loader:{'.css':'empty'},define:{'import.meta.env.VITE_WORKER_URL':'""','import.meta.env.BASE_URL':'"/"'},logLevel:'silent',
});
const output=join(dir,'ingredient.mjs');await writeFile(output,bundle.outputFiles[0].text);
// Actual renderer, shared form and both HTTP readers run with a DOM presentation double.
class Element {
 constructor(tag='',text=''){this.tagName=tag.toUpperCase();this.text=text;this.attrs={};this.children=[];this.parentNode=null;this.listeners={};this.dataset={};this.hidden=false;this.disabled=false;this.value='';this.checked=false;this.classList={add:c=>this.cls(c,true),remove:c=>this.cls(c,false),toggle:(c,v)=>this.cls(c,v)};}
 cls(c,v){const s=new Set((this.attrs.class??'').split(' ').filter(Boolean));if(v)s.add(c);else s.delete(c);this.attrs.class=[...s].join(' ');}
 setAttribute(k,v){this.attrs[k]=String(v);if(k==='value')this.value=String(v);if(k==='hidden')this.hidden=true;if(k==='disabled')this.disabled=true;if(k==='checked')this.checked=true;if(k.startsWith('data-'))this.dataset[k.slice(5)]=String(v);}
 getAttribute(k){return this.attrs[k]??null;}removeAttribute(k){delete this.attrs[k];if(k==='disabled')this.disabled=false;}
 get id(){return this.attrs.id??'';}set id(v){this.attrs.id=v;}
 get type(){return this.attrs.type??'';}get parentElement(){return this.parentNode;}
 get isConnected(){return this.tagName==='BODY'||Boolean(this.parentNode?.isConnected);}
 appendChild(c){if(typeof c==='string')c=new Element('',c);c.parentNode=this;this.children.push(c);return c;}append(...cs){cs.forEach(c=>this.appendChild(c));}
 prepend(...cs){for(const c of cs.reverse()){c.parentNode=this;this.children.unshift(c);}}
 replaceChildren(...cs){this.children.forEach(c=>c.parentNode=null);this.children=[];this.text='';this.append(...cs);}
 get textContent(){return this.text+this.children.map(c=>c.textContent).join('');}set textContent(v){this.replaceChildren();this.text=String(v);}
 remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(c=>c!==this);this.parentNode=null;}
 matches(selector){return selector.split(',').some(p=>{p=p.trim();const tag=p.match(/^[a-z]+/i)?.[0];if(tag&&this.tagName!==tag.toUpperCase())return false;for(const m of p.matchAll(/([.#])([\w-]+)/g))if(m[1]==='#'?this.id!==m[2]:!(this.attrs.class??'').split(' ').includes(m[2]))return false;for(const m of p.matchAll(/\[([\w-]+)(?:="([^"]*)")?\]/g))if(!(m[1] in this.attrs)||(m[2]!==undefined&&this.attrs[m[1]]!==m[2]))return false;return true;});}
 querySelectorAll(s){return this.children.flatMap(c=>[...(c.matches(s)?[c]:[]),...c.querySelectorAll(s)]);}querySelector(s){return this.querySelectorAll(s)[0]??null;}
 addEventListener(t,f){(this.listeners[t]??=new Set()).add(f);}removeEventListener(t,f){this.listeners[t]?.delete(f);}
 dispatchEvent(e){e.target??=this;for(const f of this.listeners[e.type]??[])f(e);return !e.defaultPrevented;}
 click(){if(!this.disabled)this.dispatchEvent({type:'click',preventDefault(){}});}focus(){document.activeElement=this;}scrollIntoView(){}
}
const A='a'.repeat(40), B='b'.repeat(40), tick=()=>new Promise(r=>setTimeout(r,0));
const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
const input=(el,selector,value)=>{const n=el.querySelector(selector);assert.ok(n,selector);n.value=value;n.dispatchEvent({type:'input'});};
const submit=el=>el.querySelector('.adm-ing-form').dispatchEvent({type:'submit',preventDefault(){}});
const clickText=(el,label)=>{const n=el.querySelectorAll('button').find(n=>n.textContent===label);assert.ok(n,label);n.click();};
let serial=0;
async function setup({mode='real',getIngredient,getCatalog}={}){
 const events={};globalThis.window={addEventListener:(t,f)=>(events[t]??=new Set()).add(f),removeEventListener:(t,f)=>events[t]?.delete(f),confirm:()=>true};
 globalThis.location={hash:'#/admin/ingredient/salt'};const storage=new Map();globalThis.sessionStorage=globalThis.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};
 globalThis.document={body:new Element('body'),createElement:tag=>new Element(tag),createTextNode:text=>new Element('',text)};Object.defineProperty(globalThis,'navigator',{configurable:true,value:{onLine:true}});
 const page=await import(`${pathToFileURL(output)}?test=${++serial}`);let identity=0,current={content:{schemaVersion:'2',name:{zh:'盐',en:'Salt'},baseUnit:'g',role:'seasoning',trackStock:false},commit:A,blobSha:'salt-a'};
 const catalog={commit:A,dishes:{soup:{schemaVersion:'3',name:{zh:'汤'}}},ingredients:{salt:current.content},suppliers:['Supplier from v3 catalog'],techniques:[],translations:{machine:0,human:0,stale:0}};
 const calls=[],legacyReads=[],writes=[],uploads=[];
 const fetch=async url=>{const path=new URL(url).pathname;calls.push(path);const body=path==='/catalog'?await(getCatalog?.()??catalog):path.startsWith('/source/ingredient/')?await(getIngredient?.(path)??structuredClone(current)):null;return new Response(JSON.stringify(body),{status:200});};
 const opts={fetch,identity:()=>identity,token:()=> 'explicit-local-fixture'};const team=page.createTeamMealsApi(mode==='unconfigured'?'':'https://fixture.invalid',{...opts,...(mode==='mock'?{mode:'mock'}:{})});const legacy=new page.HttpAdminApi('https://fixture.invalid',opts);
 for(const name of ['getCatalog','getIngredient']){const old=legacy[name].bind(legacy);legacy[name]=(...args)=>{legacyReads.push(name);return old(...args);};}
 legacy.translate=async()=>({});legacy.uploadImage=async(...args)=>{uploads.push(args);return{src:'data/ingredients/salt/images/photo.png',license:'own'};};legacy.saveIngredient=async(id,body,condition)=>{writes.push(structuredClone({id,body,condition}));current={content:structuredClone(body),commit:B,blobSha:'salt-b'};return{commit:B,blobSha:'salt-b',warnings:[],unchanged:false};};
 globalThis.__ingredientHarness={team,getLegacy(){legacyReads.push('getApi');return legacy;}};
 let el;
 async function mount(rest='salt',lang='en',same=false){location.hash='#/admin/ingredient/'+rest;if(!same){document.body.replaceChildren();el=new Element('section');document.body.append(el);}else el.replaceChildren();const promise=page.render(el,{lang,rest,planId:null,route:'admin',data:{},t:k=>k},rest,team);return{el,promise};}
 async function flush(){for(let i=0;i<8;i++)await tick();}
 function navigate(hash){location.hash=hash;for(const fn of events.hashchange??[])fn();document.body.replaceChildren();}
 function warned(){const e={preventDefault(){this.prevented=true;}};for(const f of events.beforeunload??[])f(e);return Boolean(e.prevented);}
 return{page,team,legacy,calls,legacyReads,writes,uploads,mount,flush,navigate,warned,get current(){return current;},bump(){identity++;},cleanup(){team.dispose();legacy.dispose();document.body.replaceChildren();}};
}

test('standalone real renderer accepts suppliers and duplicate names from catalog containing v3 dishes',async()=>{const s=await setup();try{const{el,promise}=await s.mount('new');await promise;await s.flush();assert.ok(el.querySelectorAll('option').some(n=>n.value==='Supplier from v3 catalog'));input(el,'#adm-ing-name-zh','盐');input(el,'#adm-ing-id','salt');assert.equal(el.querySelector('.adm-ing-dup').hidden,false);submit(el);await s.flush();assert.equal(s.writes.length,0);assert.equal(s.legacyReads.includes('getCatalog'),false);}finally{s.cleanup();}});
test('unconfigured renderer makes no legacy mock call or write form; simulation is explicit',async()=>{const s=await setup({mode:'unconfigured'});try{const{el,promise}=await s.mount();await promise;await s.flush();assert.deepEqual(s.legacyReads,[]);assert.match(el.textContent,/Not connected/);assert.equal(el.querySelector('.adm-ing-form'),null);}finally{s.cleanup();}const m=await setup({mode:'mock'});try{const{el,promise}=await m.mount();await promise;await m.flush();assert.match(el.textContent,/Simulation/);submit(el);await m.flush();assert.equal(m.writes.length,0);}finally{m.cleanup();}});
test('late source cannot paint an old language into a reused connected mount',async()=>{const wait=defer(),s=await setup({getIngredient:()=>wait.promise});try{const a=await s.mount('salt','en');const b=await s.mount('salt','uk',true);wait.resolve({content:{schemaVersion:'2',name:{zh:'盐'},baseUnit:'g',trackStock:false},commit:A,blobSha:'a'});await Promise.all([a.promise,b.promise]);await s.flush();assert.equal(b.el.querySelectorAll('.adm-ing-form').length,1);assert.doesNotMatch(b.el.textContent,/Edit ingredient/);assert.match(b.el.textContent,/Змінити інгредієнт/);}finally{s.cleanup();}});
test('late previous-session source cannot overwrite the current session',async()=>{const wait=defer();let old=true;const s=await setup({getIngredient:()=>old?wait.promise:{content:{schemaVersion:'2',name:{zh:'当前账户'},baseUnit:'g',trackStock:false},commit:B,blobSha:'b'}});try{const a=await s.mount();old=false;s.bump();s.page.changeAuth();const b=await s.mount();await b.promise;wait.resolve({content:{schemaVersion:'2',name:{zh:'旧账户'},baseUnit:'g',trackStock:false},commit:A,blobSha:'a'});await a.promise;await s.flush();assert.equal(b.el.querySelector('#adm-ing-name-zh').value,'当前账户');assert.equal(s.page.probeDraft().zh,'当前账户');}finally{s.cleanup();}});
test('raw buffer and unload protection survive leaving the ingredient route',async()=>{const s=await setup();try{let{el,promise}=await s.mount();await promise;input(el,'#adm-ing-packSize','12,');s.navigate('#/admin');assert.equal(s.warned(),true);({el,promise}=await s.mount());await promise;assert.equal(el.querySelector('#adm-ing-packSize').value,'12,');}finally{s.cleanup();}});
test('upload belongs to record across language and navigation; no repeated upload and current raw edits survive',async()=>{const s=await setup(),wait=defer();let calls=0;s.legacy.uploadImage=async()=>{calls++;await wait.promise;return{src:'data/ingredients/salt/images/photo.png',license:'own'};};try{let{el,promise}=await s.mount();await promise;const d=s.page.probeDraft();d.pending={blob:new Blob(['photo']),previewUrl:'blob:fixture',license:'own',author:'',sourceUrl:'',width:2,height:2};d.dirty=true;submit(el);await s.flush();({el,promise}=await s.mount('salt','uk'));await promise;assert.equal(el.querySelector('.adm-ing-save').disabled,true);submit(el);await s.flush();assert.equal(calls,1);input(el,'#adm-ing-name-zh','上传期间的新名字');s.navigate('#/admin');assert.equal(s.warned(),true);wait.resolve();await s.flush();({el,promise}=await s.mount());await promise;assert.equal(s.writes.length,1);assert.equal(s.writes[0].body.name.zh,'盐');assert.equal(el.querySelector('#adm-ing-name-zh').value,'上传期间的新名字');assert.equal(s.warned(),true);submit(el);await s.flush();assert.equal(calls,1);assert.deepEqual(s.writes[1].condition,{ifMatch:'salt-b'});}finally{wait.resolve();s.cleanup();}});
test('save pending survives rebind, acknowledges snapshot only and uses its returned blob for next save',async()=>{const s=await setup(),wait=defer();const old=s.legacy.saveIngredient;s.legacy.saveIngredient=async(...args)=>{const result=await old(...args);await wait.promise;return result;};try{let{el,promise}=await s.mount();await promise;input(el,'#adm-ing-name-zh','提交名字');submit(el);await s.flush();({el,promise}=await s.mount('salt','uk'));await promise;assert.equal(el.querySelector('.adm-ing-save').disabled,true);input(el,'#adm-ing-name-zh','稍后名字');submit(el);await s.flush();assert.equal(s.writes.length,1);wait.resolve();await s.flush();assert.equal(s.warned(),true);assert.equal(el.querySelector('#adm-ing-name-zh').value,'稍后名字');submit(el);await s.flush();assert.deepEqual(s.writes[1].condition,{ifMatch:'salt-b'});}finally{wait.resolve();s.cleanup();}});
test('unknown save does not resend across navigation; force read verifies exact body and retains newer raw input',async()=>{const s=await setup();const normal=s.legacy.saveIngredient;s.legacy.saveIngredient=async(...args)=>{await normal(...args);throw new TypeError('reply lost');};try{let{el,promise}=await s.mount();await promise;input(el,'#adm-ing-name-zh','提交名字');submit(el);await s.flush();s.navigate('#/admin');({el,promise}=await s.mount('salt','en'));await promise;assert.match(el.textContent,/outcome unknown/);assert.equal(el.querySelector('.adm-ing-save').disabled,true);input(el,'#adm-ing-name-zh','更新名字');clickText(el,'Verify save outcome');await s.flush();assert.equal(s.writes.length,1);assert.equal(el.querySelector('#adm-ing-name-zh').value,'更新名字');assert.equal(el.querySelector('.adm-ing-save').disabled,false);assert.equal(s.warned(),true);assert.ok(s.calls.filter(p=>p==='/source/ingredient/salt').length>=2);}finally{s.cleanup();}});
test('unknown upload remains protected because a source read cannot prove the upload result',async()=>{const s=await setup();let uploads=0;s.legacy.uploadImage=async()=>{uploads++;throw new TypeError('reply lost');};try{let{el,promise}=await s.mount();await promise;const d=s.page.probeDraft();d.pending={blob:new Blob(['photo']),previewUrl:'blob:fixture',license:'own',author:'',sourceUrl:'',width:2,height:2};d.dirty=true;submit(el);await s.flush();s.navigate('#/admin');({el,promise}=await s.mount('salt','en'));await promise;submit(el);await s.flush();assert.equal(uploads,1);assert.match(el.textContent,/outcome unknown/);assert.equal(s.warned(),true);assert.equal(el.querySelector('.adm-ing-save').disabled,true);}finally{s.cleanup();}});

test('shared form keeps default translation behavior and an explicit declined task sends nothing',async()=>{const s=await setup();try{let translations=0;const api={...s.legacy,translate:async()=>{translations++;return{en:'Translated',uk:'Переклад'};}};const d=s.page.createIngredientDraft({zh:'名称'});s.page.buildIngredientForm({lang:'en',api,draft:d,editing:false,catalog:null});await s.flush();assert.equal(translations,1);assert.equal(d.en,'Translated');assert.equal(d.uk,'Переклад');const other=s.page.createIngredientDraft({zh:'不发出'});s.page.buildIngredientForm({lang:'en',api,draft:other,editing:false,catalog:null,onTaskStart:()=>null});await s.flush();assert.equal(translations,1);assert.equal(other.en,'');}finally{s.cleanup();}});
test('translation owner survives language and ignores a result after newer raw name edits',async()=>{const s=await setup(),wait=defer();let calls=0;s.legacy.translate=async()=>{calls++;return wait.promise;};try{let{el,promise}=await s.mount();await promise;input(el,'#adm-ing-name-zh','新中文');el.querySelector('#adm-ing-name-zh').dispatchEvent({type:'change'});await s.flush();({el,promise}=await s.mount('salt','uk'));await promise;assert.equal(el.querySelector('.adm-ing-save').disabled,true);assert.equal(el.querySelector('.adm-ing-translate').disabled,true);input(el,'#adm-ing-name-en','Later user English');wait.resolve({en:'Late translation',uk:'Пізній переклад'});await s.flush();assert.equal(calls,1);assert.equal(el.querySelector('#adm-ing-name-en').value,'Later user English');assert.equal(el.querySelector('.adm-ing-save').disabled,false);assert.equal(s.warned(),true);}finally{wait.resolve({});s.cleanup();}});
test('photo decode is busy before a preview exists and its result survives language/navigation',async()=>{const s=await setup(),images=[];globalThis.Image=class{naturalWidth=2;naturalHeight=2;set src(v){images.push(this);}};try{let{el,promise}=await s.mount();await promise;const file=new Blob(['tiny'],{type:'image/png'});const picker=el.querySelector('#adm-ing-photo-pick');picker.files=[file];picker.dispatchEvent({type:'change'});assert.equal(images.length,1);assert.equal(el.querySelector('.adm-ing-save').disabled,true);s.navigate('#/admin');assert.equal(s.warned(),true);({el,promise}=await s.mount('salt','uk'));await promise;assert.equal(el.querySelector('.adm-ing-save').disabled,true);images[0].onload();await s.flush();assert.ok(el.querySelector('.adm-ing-preview'));assert.equal(s.page.probeDraft().pending.blob,file);assert.equal(el.querySelector('.adm-ing-save').disabled,false);assert.equal(s.warned(),true);}finally{s.cleanup();}});
test('photo decode failure releases busy while keeping prior photo and raw edits',async()=>{const s=await setup(),images=[];globalThis.Image=class{set src(v){images.push(this);}};try{let{el,promise}=await s.mount();await promise;const d=s.page.probeDraft();d.image={src:'data/ingredients/salt/images/previous.png',license:'own'};const picker=el.querySelector('#adm-ing-photo-pick');picker.files=[new Blob(['bad'],{type:'image/png'})];picker.dispatchEvent({type:'change'});s.navigate('#/admin');images[0].onerror();await s.flush();({el,promise}=await s.mount('salt','uk'));await promise;assert.equal(d.image.src,'data/ingredients/salt/images/previous.png');assert.equal(el.querySelector('.adm-ing-save').disabled,false);assert.equal(s.warned(),true);}finally{s.cleanup();}});
test('successful translation from an old language view updates the current view without repeating',async()=>{const s=await setup(),wait=defer();let calls=0;s.legacy.translate=async()=>{calls++;return wait.promise;};try{let{el,promise}=await s.mount();await promise;el.querySelector('.adm-ing-translate').click();({el,promise}=await s.mount('salt','uk'));await promise;wait.resolve({en:'Updated English',uk:'Оновлений переклад'});await s.flush();assert.equal(el.querySelector('#adm-ing-name-en').value,'Updated English');assert.equal(el.querySelector('#adm-ing-name-uk').value,'Оновлений переклад');assert.equal(calls,1);assert.equal(el.querySelector('.adm-ing-save').disabled,false);}finally{wait.resolve({});s.cleanup();}});
test('malformed successful save responses stay unknown and cannot discard the pending attempt',async()=>{const s=await setup();s.legacy.saveIngredient=async()=>({});try{const{el,promise}=await s.mount();await promise;submit(el);await s.flush();assert.match(el.textContent,/outcome unknown/);assert.equal(el.querySelector('.adm-ing-save').disabled,true);assert.equal(s.warned(),true);}finally{s.cleanup();}});
test('unrecognized write rejection cannot be assumed safe to retry',async()=>{const s=await setup();s.legacy.saveIngredient=async()=>{throw new s.page.ApiError(200,'bad_response','');};try{const{el,promise}=await s.mount();await promise;submit(el);await s.flush();assert.match(el.textContent,/outcome unknown/);assert.equal(el.querySelector('.adm-ing-save').disabled,true);}finally{s.cleanup();}});
test('field validation survives language and does not steal focus on every later keystroke',async()=>{const s=await setup();s.legacy.saveIngredient=async()=>{throw new s.page.ApiError(400,'required','Server requires a name',[{path:'/name',code:'required',message:'Server requires a name'}]);};try{let{el,promise}=await s.mount();await promise;submit(el);await s.flush();({el,promise}=await s.mount('salt','uk'));await promise;assert.match(el.textContent,/Server requires a name/);const field=el.querySelector('#adm-ing-supplier');field.focus();input(el,'#adm-ing-supplier','Later supplier');assert.equal(document.activeElement,field);assert.match(el.textContent,/Server requires a name/);}finally{s.cleanup();}});
