import assert from 'node:assert/strict';import {test} from 'node:test';import {setup} from './team-meals-pages-guard-harness.mjs';
const B='b'.repeat(40), ack=commit=>({commit,blobSha:'explicit-fixture-blob',unchanged:false,warnings:[]});
async function start(s,page,expected='saving'){await s.mount(page);if(page==='ingredient'){s.input('#adm-ing-name-zh','Submitted ingredient');s.el.querySelector('form').dispatchEvent({type:'submit',preventDefault(){}});}else{s.click('Add an ingredient');s.el.querySelector('.adm-dish-result-new').click();await s.flush();const inline=s.el.querySelector('.adm-dish-inline');const field=suffix=>inline.querySelectorAll('input').find(n=>n.id.endsWith(suffix)).id;s.input('#'+field('-name-zh'),'Inline ingredient');s.input('#'+field('-id'),'inline-local');s.click('Save this ingredient');}await s.flush();assert.equal(s.m.inspectReloadSafety().reason,expected);}
for(const page of ['ingredient','dish'])for(const old of [false,true])for(const valid of [false,true])test(`${page}: ${old?'available old-auth':'actual Http current-auth'} ${valid?'string':'array'} ACK ${valid?'settles only its write':'cannot prove completion'}`,async()=>{
 const s=await setup();try{const gate=s.holdWrite();let visibleCalls=0;if(old)s.legacy.saveIngredient=()=>{visibleCalls++;return gate.promise;};await start(s,page);if(old){s.auth();s.home();assert.equal(s.m.inspectReloadSafety().reason,'unknown');}
 gate.resolve(old?ack(valid?B:[B]):Response.json({ok:true,...ack(valid?B:[B])}));await s.flush();
 const state=s.m.inspectReloadSafety();assert.equal(state.reason,valid?(old?'clear':page==='dish'?'dirty':'clear'):'unknown',JSON.stringify(state));assert.equal(old?visibleCalls:s.counts.writes,1);
 if(!old&&!valid){assert.equal(page==='ingredient'?s.el.querySelector('.adm-ing-save').disabled:s.el.querySelector('.adm-dish-save-draft').disabled,true);if(page==='ingredient')assert.match(s.el.textContent,/outcome unknown/);else assert.ok(s.el.querySelector('.adm-dish-inline'),'unproven inline ingredient remains raw');}
 }finally{s.cleanup();}
});
for(const page of ['ingredient','dish'])test(`${page}: real Http old-auth hides even a valid ACK and its unknown write remains protected`,async()=>{const s=await setup();try{const gate=s.holdWrite();await start(s,page);s.auth();s.home();gate.resolve(Response.json({ok:true,...ack(B)}));await s.flush();assert.equal(s.m.inspectReloadSafety().reason,'unknown');assert.equal(s.counts.writes,1);}finally{s.cleanup();}});
for(const page of ['ingredient','dish'])test(`${page}: valid available old ACK settles A only while B still owns its write`,async()=>{
 const s=await setup();let finishA,finishB;const a=new Promise(r=>finishA=r),b=new Promise(r=>finishB=r);let calls=0;
 try{s.legacy.saveIngredient=()=>++calls===1?a:b;await start(s,page);s.auth();s.home();await start(s,page,'unknown');assert.equal(s.m.inspectReloadSafety().reason,'unknown');finishA(ack(B));await s.flush();const active=s.m.inspectReloadSafety();assert.equal(active.reason,'saving');assert.equal(active.records.some(r=>r.id==='previous-session-operation'),false);assert.equal(calls,2);finishB(ack([B]));await s.flush();assert.equal(s.m.inspectReloadSafety().reason,'unknown');assert.equal(calls,2);}finally{finishA(ack(B));finishB(ack(B));s.cleanup();}
});
