/** D composition regression: real Plan + Import renderers, C1 API/session/store, local HTTP envelopes. */
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm,readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {tmpdir} from 'node:os';
import {dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {test,after} from 'node:test';
const here=dirname(fileURLToPath(import.meta.url)),req=createRequire(import.meta.url),vr=createRequire(req.resolve('vite/package.json')),esbuild=await import(pathToFileURL(vr.resolve('esbuild')));
const dir=await mkdtemp(join(tmpdir(),'plan-import-composition-'));after(()=>rm(dir,{recursive:true,force:true}));
const built=await esbuild.build({stdin:{contents:`export {createPlanRenderer} from './src/pages/admin/plan';export {createPlanForm} from './src/pages/admin/plan-form';export {applyPlanImport} from './src/pages/admin/plan-import';export {render as renderImport} from './src/pages/admin/import';export {createTeamMealsApi} from './src/api/team-meals';export {clearToken as changeAuth} from './src/admin/token';export {inspectReloadSafety,createPageReloadCoverage} from './src/view-models/reload-safety';export {bindDraftStore} from './src/admin/store';`,resolveDir:join(here,'..')},bundle:true,write:false,format:'esm',platform:'browser',loader:{'.css':'empty'},define:{'import.meta.env.VITE_WORKER_URL':'""','import.meta.env.BASE_URL':'"/"'},logLevel:'silent',plugins:[{name:'read-actual-plan-session',setup(build){build.onLoad({filter:/\/pages\/admin\/plan\.ts$/},async args=>({contents:(await readFile(args.path,'utf8')).replace('return Object.assign(renderPlan,{','return Object.assign(renderPlan,{readSession:()=>form.session,'),loader:'ts'}));}}]});
const file=join(dir,'pages.mjs');await writeFile(file,built.outputFiles[0].text);
let mutations=()=>{};
class Element{
 constructor(tag='',text=''){this.tagName=tag.toUpperCase();this.text=text;this.children=[];this.attrs={};this.listeners={};this.style={};this.value='';this.disabled=false;this.validity={badInput:false};this.parentNode=null;this.classList={add:x=>this.setAttribute('class',`${this.attrs.class??''} ${x}`),remove:x=>this.setAttribute('class',(this.attrs.class??'').split(' ').filter(v=>v!==x).join(' '))};}
 setAttribute(k,v){this.attrs[k]=String(v);if(k==='value')this.value=String(v);if(k==='disabled')this.disabled=true;}getAttribute(k){return this.attrs[k]??null;}removeAttribute(k){delete this.attrs[k];if(k==='disabled')this.disabled=false;}
 get dataset(){return Object.fromEntries(Object.entries(this.attrs).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5),v]));}
 appendChild(c){if(typeof c==='string')c=new Element('',c);c.parentNode=this;this.children.push(c);if(this.tagName==='SELECT'&&c.tagName==='OPTION'&&(this.children.length===1||c.attrs.selected!==undefined))this.value=c.attrs.value??'';mutations();return c;}append(...cs){cs.forEach(c=>this.appendChild(c));}prepend(c){this.insertBefore(c,this.children[0]);}insertBefore(c,b){c.parentNode=this;const i=this.children.indexOf(b);this.children.splice(i<0?this.children.length:i,0,c);mutations();return c;}replaceChildren(...cs){this.children.forEach(c=>c.parentNode=null);this.children=[];this.text='';this.append(...cs);mutations();}remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(c=>c!==this);this.parentNode=null;mutations();}
 get firstChild(){return this.children[0]??null;}get isConnected(){return this.tagName==='BODY'||!!this.parentNode?.isConnected;}get childElementCount(){return this.children.filter(c=>c.tagName).length;}get textContent(){return this.text+this.children.map(c=>c.textContent).join('');}set textContent(s){this.replaceChildren();this.text=String(s);}
 addEventListener(t,f){(this.listeners[t]??=[]).push(f);}dispatch(t){if(t==='click'&&this.disabled)return;for(const fn of this.listeners[t]??[])fn({target:this,preventDefault(){}});}click(){this.dispatch('click');}focus(){document.activeElement=this;}scrollIntoView(){}
 querySelector(s){return this.querySelectorAll(s)[0]??null;}querySelectorAll(s){return walk(this).slice(1).filter(el=>{const m=s.match(/^\[([^=]+)="([^"]+)"\]$/);return m?el.attrs[m[1]]===m[2]:s.startsWith('.')?(el.attrs.class??'').split(' ').includes(s.slice(1)):s.startsWith('#')?el.attrs.id===s.slice(1):el.tagName===s.toUpperCase();});}
}
const walk=n=>[n,...n.children.flatMap(walk)],focus=(el,key)=>el.querySelector(`[data-focus="${key}"]`),cls=(el,name)=>el.querySelector(`.${name}`),tick=()=>new Promise(r=>setImmediate(r));
const input=(el,key,value,event='input')=>{const node=focus(el,key);assert.ok(node,key);node.value=value;node.dispatch(event);};
const save=el=>cls(el,'tm-actions')?.querySelector('button'),count=(el,index)=>focus(el,`servings-${index}`)?.value;
const remove=(el,index)=>el.querySelector(`[data-meal-index="${index}"]`).querySelector('button').click();
const rows=el=>walk(el).filter(n=>n.attrs['data-meal-index']!==undefined),phase=el=>walk(el).find(n=>n.attrs['data-phase'])?.attrs['data-phase'];
const A='a'.repeat(40),raw='2.0000000000000001';
const base=count=>({schemaVersion:'3',name:{zh:'原计划',en:'Original plan'},margin:1.17,dateRange:{start:'2026-09-01',end:'2026-09-30'},meals:[{date:'2026-09-14',mealType:'lunch',dishRef:'soup',plannedServings:count,serviceWindow:'12:00-13:00'},{date:'2026-09-16',mealType:'dinner',dishRef:'stew',plannedServings:12},{date:'2026-09-17',mealType:'lunch',dishRef:'soup',plannedServings:5}]});
let serial=0;
async function setup(){
 const names=['HTMLElement','MutationObserver','window','location','document','localStorage','sessionStorage','navigator'],prior=new Map(names.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)])),observers=new Set(),timers=new Set();let queued=false;
 mutations=()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;for(const callback of [...observers])callback();});};
 Object.defineProperty(globalThis,'navigator',{configurable:true,writable:true,value:{onLine:true}});
 globalThis.HTMLElement=Element;globalThis.MutationObserver=class{constructor(fn){this.fn=fn;}observe(){observers.add(this.fn);}disconnect(){observers.delete(this.fn);}};
 globalThis.window={addEventListener(){},confirm:()=>true,setTimeout(fn,ms){const id=setTimeout(fn,ms);timers.add(id);return id;},clearTimeout};globalThis.location={hash:'#/admin/plan/week-a'};globalThis.document={body:new Element('body'),createElement:t=>new Element(t),createTextNode:t=>new Element('',t),activeElement:null};
 const storage=new Map();globalThis.localStorage=globalThis.sessionStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};
 const page=await import(`${pathToFileURL(file)}?case=${++serial}`),calls=[],writes=[],gates=[],sources=new Map(['week-a','week-b'].map((id,i)=>[id,{content:base(i?18:2),commit:A,blobSha:`initial-${id}`}]));let identity=1,seq=0,post='success';
 const json=x=>Response.json(structuredClone(x)),failure=(status,code)=>Response.json({ok:false,errors:[{path:'',code,message:code}]},{status});
 const api=page.createTeamMealsApi(`https://plan-import-${serial}.invalid`,{mode:'mock',token:()=>`explicit-local-${identity}`,identity:()=>identity,fetch:async(url,init)=>{
  const u=new URL(url),call={path:u.pathname,method:init.method,revision:u.searchParams.get('revision'),identity};calls.push(call);
  const gate=gates.find(g=>!g.claimed&&g.match(call));if(gate){gate.claimed=true;await gate.promise;if(gate.fail)return failure(503,'upstream_unavailable');}
  if(init.method==='POST'){
   const body=JSON.parse(init.body),id=u.pathname.split('/').at(-1),headers=new Headers(init.headers);writes.push({id,body,match:headers.get('If-Match'),none:headers.get('If-None-Match')});
   if(post==='conflict'){post='success';return failure(409,'conflict');}
   const commit=(++seq).toString(16).padStart(40,'0'),blobSha=`saved-${seq}`;sources.set(id,{content:body,commit,blobSha});if(post==='lost'){post='success';throw new TypeError('explicit lost response');}return json({commit,blobSha,unchanged:false,warnings:[]});
  }
  if(u.pathname==='/catalog')return json({commit:call.revision??A,dishes:{soup:{schemaVersion:'3',name:{zh:'原汤',en:'Soup',uk:'Суп'},status:'active',components:[]},stew:{schemaVersion:'3',name:{zh:'炖菜',en:'Stew',uk:'Рагу'},status:'active',components:[]}},ingredients:{},techniques:[],suppliers:[],translations:{machine:0,human:0,stale:0}});
  if(u.pathname.startsWith('/source/plan/')){const value=sources.get(u.pathname.split('/').at(-1));return value?json(value):failure(404,'not_found');}throw new Error(`Unexpected request ${u.pathname}`);
 }});
 const plan=page.createPlanRenderer(api),coverage=page.createPageReloadCoverage();
 const fresh=(route,id,lang)=>{document.body.replaceChildren();const el=new Element('main');document.body.append(el);location.hash=`#/admin/plan/${id}${route==='import'?'/import':''}`;return{el,ctx:{lang,route:'admin',rest:id,planId:id,setReloadCoverage:coverage.beginRender('admin',`plan/${id}${route==='import'?'/import':''}`)}};};
 const f={page,api,plan,session:()=>plan.readSession(),calls,writes,sources,async planPage(id='week-a',lang='en'){const {el,ctx}=fresh('plan',id,lang);await plan(el,ctx,id);return el;},async importPage(text='2026-09-15 午 原汤',id='week-a',lang='zh',scopeApi=api){const {el,ctx}=fresh('import',id,lang);await page.renderImport(el,ctx,id,scopeApi);const ta=cls(el,'adm-import-ta');if(text!==null){ta.value=text;ta.dispatch('input');cls(el,'adm-import-parse').click();}return el;},submit(el){const b=cls(el,'adm-import-submit');assert.ok(b);assert.equal(b.disabled,false,el.textContent);b.click();},async flush(){for(let i=0;i<12;i++)await tick();},hold(match){let release;const promise=new Promise(r=>release=r),g={match,promise,release,claimed:false};gates.push(g);return g;},post(value){post=value;},auth(){identity++;page.changeAuth();},leave(){document.body.replaceChildren();location.hash='#/menu';},async cleanup(){for(const g of gates)g.release();for(const t of timers)clearTimeout(t);api.dispose();document.body.replaceChildren();await tick();observers.clear();mutations=()=>{};for(const [k,v] of prior){if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}}};
 return f;
}
async function savedEight(f){const el=await f.planPage();input(el,'servings-0','8');save(el).click();await f.flush();assert.equal(f.writes.length,1);assert.equal(phase(el),'saved-but-unpublished');return el;}
async function importedReturn(f,text='2026-09-15 午 原汤',id='week-a'){const el=await f.importPage(text,id);f.submit(el);await f.flush();return f.planPage(id);}

test('real page handoff preserves unsaved eleven when importing another meal and issues no extra POST',async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-0','11');el=await importedReturn(f);assert.equal(count(el,0),'11');assert.equal(rows(el).length,4);assert.equal(count(el,1),'');assert.equal(f.writes.length,1);save(el).click();await f.flush();assert.equal(f.writes[1].match,'saved-1');assert.equal(f.writes[1].body.meals[0].plannedServings,11);assert.equal(Object.hasOwn(f.writes[1].body.meals[1],'plannedServings'),false);}finally{await f.cleanup();}});
test('deliberately omitted local count is retained when another meal is imported',async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-0','');el=await importedReturn(f);assert.equal(count(el,0),'');save(el).click();await f.flush();assert.equal(Object.hasOwn(f.writes.at(-1).body.meals[0],'plannedServings'),false);}finally{await f.cleanup();}});
test('local added/deleted rows and whole-plan metadata survive a new import',async()=>{const f=await setup();try{let el=await savedEight(f);remove(el,1);input(el,'add-date','2026-09-18');input(el,'add-dish','stew','change');cls(el,'tm-add-form').dispatch('submit');el=await importedReturn(f);save(el).click();await f.flush();const plan=f.writes.at(-1).body;assert.ok(!plan.meals.some(m=>m.date==='2026-09-16'));assert.ok(plan.meals.some(m=>m.date==='2026-09-18'&&m.dishRef==='stew'&&!Object.hasOwn(m,'plannedServings')));assert.equal(plan.margin,1.17);assert.deepEqual(plan.dateRange,{start:'2026-09-01',end:'2026-09-30'});assert.equal(plan.meals[0].serviceWindow,'12:00-13:00');}finally{await f.cleanup();}});
test('sorting imported rows preserves invalid raw on its original row and leaves Add choices pending',async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-1',raw);input(el,'add-date','2026-09-19');input(el,'add-dish','stew','change');el=await importedReturn(f,'2026-09-13 午 原汤');assert.equal(count(el,2),raw);assert.equal(focus(el,'servings-2').attrs['aria-invalid'],'true');assert.equal(count(el,1),'8');assert.equal(save(el).disabled,true);assert.equal(focus(el,'add-date').value,'2026-09-19');assert.equal(focus(el,'add-dish').value,'stew');assert.equal(f.plan.readAuxiliary('week-a').dirty,true);assert.equal(f.writes.length,1);}finally{await f.cleanup();}});
test('A is resumed by ID after visiting B; importing A cannot use B or saved A as its current draft',async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-0','11');el=await f.planPage('week-b');input(el,'servings-0','21');el=await importedReturn(f);assert.equal(count(el,0),'11');assert.equal(rows(el).length,4);el=await f.planPage('week-b');assert.equal(count(el,0),'21');assert.equal(rows(el).length,3);}finally{await f.cleanup();}});
test('import edits the original saving document; its late ACK cannot consume the later merged draft',async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-0','9');const held=f.hold(c=>c.method==='POST');save(el).click();await f.flush();input(el,'servings-0','11');el=await importedReturn(f);assert.equal(phase(el),'saving');assert.equal(count(el,0),'11');assert.equal(rows(el).length,4);held.release();await f.flush();assert.equal(phase(el),'dirty');assert.equal(f.writes.length,2);assert.equal(f.writes[1].body.meals.length,3);save(el).click();await f.flush();assert.equal(f.writes[2].match,'saved-2');assert.equal(f.writes[2].body.meals[0].plannedServings,11);}finally{await f.cleanup();}});
for(const mode of ['lost','conflict'])test(`${mode}: import changes only local draft and preserves original unresolved/conflict save state`,async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-0','11');f.post(mode);save(el).click();await f.flush();const expected=mode==='lost'?'outcome-unknown':'conflict';assert.equal(phase(el),expected);el=await importedReturn(f);assert.equal(phase(el),expected);assert.equal(count(el,0),'11');assert.equal(rows(el).length,4);assert.equal(f.writes.length,2);assert.equal(save(el).disabled,true);}finally{await f.cleanup();}});
test('an unvisited Plan still uses the guarded saved-source/store handoff without creating a write',async()=>{const f=await setup();try{const el=await f.importPage();f.submit(el);await f.flush();assert.equal(f.writes.length,0);const store=f.page.bindDraftStore(f.api),draft=store.getDraftPlan('week-a');assert.equal(draft.meals.length,4);assert.equal(draft.meals[0].plannedServings,2);assert.equal(store.undoDraftPlan('week-a'),true);assert.equal(store.getDraftPlan('week-a'),null);}finally{await f.cleanup();}});
for(const mode of ['omitted','specified','clear'])test(`${mode}: matching import affects only the first duplicate and preserves the other locally edited duplicate`,async()=>{const f=await setup();try{
 const source=f.sources.get('week-a');source.content.meals.push({...source.content.meals[0],plannedServings:6,serviceWindow:'13:00-14:00'});let el=await savedEight(f);input(el,'servings-0','11');input(el,'servings-3','13');
 el=await f.importPage(`2026-09-14 午 原汤${mode==='omitted'?'':' 4'}`);if(mode==='clear')cls(el,'adm-import-clear-servings').click();f.submit(el);await f.flush();el=await f.planPage();assert.equal(count(el,0),mode==='omitted'?'11':mode==='specified'?'4':'');assert.equal(count(el,1),'13');save(el).click();await f.flush();const plan=f.writes.at(-1).body;assert.equal(plan.meals[1].serviceWindow,'13:00-14:00');assert.equal(plan.meals.filter(m=>m.date==='2026-09-14'&&m.dishRef==='soup').length,2);
 }finally{await f.cleanup();}});
test('cancelling Import leaves the current Plan draft and raw Import input untouched',async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-0','11');await f.importPage();el=await f.planPage();assert.equal(count(el,0),'11');assert.equal(rows(el).length,3);el=await f.importPage(null);assert.equal(cls(el,'adm-import-ta').value,'2026-09-15 午 原汤');assert.equal(f.writes.length,1);}finally{await f.cleanup();}});
for(const mode of ['omitted','specified','clear'])test(`${mode}: explicit import intent controls the matching row raw override while preserving unrelated invalid input`,async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-0',raw);input(el,'servings-1','1.5');el=await f.importPage(`2026-09-14 午 原汤${mode==='omitted'?'':' 4'}`);if(mode==='clear')cls(el,'adm-import-clear-servings').click();f.submit(el);await f.flush();el=await f.planPage();assert.equal(count(el,0),mode==='omitted'?raw:mode==='specified'?'4':'');assert.equal(count(el,1),'1.5');assert.equal(focus(el,'servings-0').attrs['aria-invalid']==='true',mode==='omitted');assert.equal(save(el).disabled,true);assert.equal(f.writes.length,1);}finally{await f.cleanup();}});

test('a genuinely closed known C1 owner refuses Import and cannot fall back to GET/store',async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-0','11');const session=f.session();el=await f.importPage();assert.equal(session.dispose(),true);const reads=f.calls.length;f.submit(el);await f.flush();assert.equal(f.calls.length,reads);assert.equal(location.hash,'#/admin/plan/week-a/import');assert.equal(cls(el,'adm-import-ta').value,'2026-09-15 午 原汤');assert.match(el.textContent,/输入尚未应用/);assert.equal(f.page.bindDraftStore(f.api).getDraftPlan('week-a'),null);assert.equal(f.writes.length,1);}finally{await f.cleanup();}});
test('a retired auth capability does not downgrade a new Import attempt to saved-source fallback',async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-0','11');f.auth();el=await f.importPage();const reads=f.calls.length;f.submit(el);await f.flush();assert.equal(f.calls.length,reads);assert.equal(location.hash,'#/admin/plan/week-a/import');assert.match(el.textContent,/输入尚未应用/);assert.equal(cls(el,'adm-import-ta').value,'2026-09-15 午 原汤');el=await f.planPage();assert.equal(count(el,0),'8');el=await importedReturn(f);assert.equal(count(el,0),'8');assert.equal(rows(el).length,4);}finally{await f.cleanup();}});
for(const change of ['route','language','input'])test(`${change}: a synchronous C1 edit subscriber cannot trigger stale Import success/navigation or leave old store content to overwrite the merge`,async()=>{const f=await setup();let stop=()=>{};try{let el=await savedEight(f);input(el,'servings-0','11');const session=f.session();el=await f.importPage();const oldImport=el;f.page.bindDraftStore(f.api).setDraftPlan('week-a',base(3),'import');let fired=false,rebound;
 stop=session.subscribe(s=>{if(fired||s.draft?.meals.length!==4)return;fired=true;if(change==='route')f.leave();else if(change==='language')rebound=f.importPage(null,'week-a','uk');else {const ta=cls(oldImport,'adm-import-ta');ta.value='2026-09-19 午 原汤';ta.dispatch('input');}});
 f.submit(el);await f.flush();if(rebound)el=await rebound;assert.equal(fired,true);assert.equal(f.page.bindDraftStore(f.api).getDraftPlan('week-a'),null);assert.equal(location.hash,change==='route'?'#/menu':'#/admin/plan/week-a/import');assert.ok(f.page.inspectReloadSafety().records.some(r=>r.kind==='import'&&r.dirty));stop();el=await f.planPage();assert.equal(count(el,0),'11');assert.equal(rows(el).length,4);if(change==='input'){el=await f.importPage(null);assert.equal(cls(el,'adm-import-ta').value,'2026-09-19 午 原汤');}assert.equal(f.writes.length,1);
 }finally{stop();await f.cleanup();}});
for(const change of ['route','language','input','auth','failure'])test(`${change}: an unvisited-document fallback read retains input and cannot create a stale handoff`,async()=>{const f=await setup();try{let el=await f.importPage();const held=f.hold(c=>c.path==='/source/plan/week-a');f.submit(el);await f.flush();assert.equal(held.claimed,true);if(change==='route')f.leave();if(change==='language')el=await f.importPage(null,'week-a','uk');if(change==='input'){const ta=cls(el,'adm-import-ta');ta.value='2026-09-19 午 原汤';ta.dispatch('input');}if(change==='auth')f.auth();if(change==='failure')held.fail=true;held.release();await f.flush();assert.equal(f.page.bindDraftStore(f.api).getDraftPlan('week-a'),null);assert.equal(f.writes.length,0);if(change!=='auth'&&change!=='route')assert.ok(cls(el,'adm-import-ta').value.includes(change==='input'?'2026-09-19':'2026-09-15'));if(change==='failure'){f.submit(el);await f.flush();assert.equal(f.page.bindDraftStore(f.api).getDraftPlan('week-a').meals.length,4);}
 }finally{await f.cleanup();}});
test('unknown save recovery verifies its original request and leaves the later imported draft dirty',async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-0','11');f.post('lost');save(el).click();await f.flush();el=await importedReturn(f);const before=f.writes.length;walk(el).find(n=>n.tagName==='BUTTON'&&n.textContent==='Verify save outcome').click();await f.flush();assert.equal(phase(el),'dirty');assert.equal(count(el,0),'11');assert.equal(rows(el).length,4);assert.equal(f.writes.length,before);save(el).click();await f.flush();assert.equal(f.writes.at(-1).match,'saved-2');assert.equal(f.writes.at(-1).body.meals.length,4);}finally{await f.cleanup();}});
test('repeated explicit import is idempotent and a later new Plan edit survives returning without resubmitting',async()=>{const f=await setup();try{let el=await savedEight(f);input(el,'servings-0','11');el=await importedReturn(f);assert.equal(rows(el).length,4);el=await importedReturn(f);assert.equal(rows(el).length,4);input(el,'servings-0','15');await f.importPage(null);el=await f.planPage();assert.equal(count(el,0),'15');assert.equal(rows(el).length,4);assert.equal(f.writes.length,1);}finally{await f.cleanup();}});
test('same ID through a different real API instance cannot read or edit the first API draft',async()=>{const f=await setup();let other;try{let el=await savedEight(f);input(el,'servings-0','11');const calls=[];other=f.page.createTeamMealsApi('https://other-plan-owner.invalid',{mode:'mock',identity:()=>1,token:()=>'explicit-other-owner',fetch:async(url,init)=>{const u=new URL(url);calls.push(u.pathname);assert.equal(init.method,'GET');return u.pathname==='/catalog'?Response.json({commit:A,dishes:{soup:{schemaVersion:'3',name:{zh:'原汤'},status:'active',components:[]}},ingredients:{},techniques:[],suppliers:[],translations:{machine:0,human:0,stale:0}}):Response.json({content:base(20),commit:A,blobSha:'other-lock'});}});el=await f.importPage(undefined,'week-a','zh',other);f.submit(el);await f.flush();assert.equal(f.page.bindDraftStore(other).getDraftPlan('week-a').meals[0].plannedServings,20);assert.ok(calls.includes('/source/plan/week-a'));el=await f.planPage();assert.equal(count(el,0),'11');assert.equal(rows(el).length,3);assert.equal(f.writes.length,1);}finally{other?.dispose();await f.cleanup();}});
// Additional adapter boundary probe: actual C1 edit refuses an invalidated context;
// the injected page raw-remap hook must restore its old map. Main cases above use both real renderers.
test('a C1-refused edit rolls back the page raw remap and leaves the document intact',async()=>{const f=await setup();try{let rawMap=new Map([[0,raw]]),before=rawMap;const form=f.page.createPlanForm(f.api,{remapRows(){rawMap=new Map();form.session.invalidate();return()=>{rawMap=before;};}});await form.load('week-a');form.servings(0,'11');const result=f.page.applyPlanImport(f.api,'week-a',base=>({plan:{...base,meals:[...base.meals,{date:'2026-09-15',mealType:'lunch',dishRef:'soup'}]},order:[0,1,2,-1]}),()=>true);assert.equal(result,'rejected');assert.equal(rawMap,before);await form.load('week-a');assert.equal(form.session.getState().draft.meals[0].plannedServings,11);assert.equal(form.session.getState().draft.meals.length,3);assert.equal(f.writes.length,0);}finally{await f.cleanup();}});
