import assert from 'node:assert/strict';
import {readFile,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {tmpdir} from 'node:os';
import {dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {test,after} from 'node:test';
const here=dirname(fileURLToPath(import.meta.url)),require=createRequire(import.meta.url),vr=createRequire(require.resolve('vite/package.json')),esbuild=await import(pathToFileURL(vr.resolve('esbuild')));
const dir=await mkdtemp(join(tmpdir(),'plan-raw-owner-'));after(()=>rm(dir,{recursive:true,force:true}));
const entry=join(here,'../src/pages/admin/plan.ts'),bundle=await esbuild.build({stdin:{contents:await readFile(entry,'utf8')+`\nexport {createTeamMealsApi} from ${JSON.stringify(join(here,'../src/api/team-meals.ts'))};\nexport {clearToken as changeAuth} from ${JSON.stringify(join(here,'../src/admin/token.ts'))};\nexport {inspectReloadSafety,createPageReloadCoverage} from ${JSON.stringify(join(here,'../src/view-models/reload-safety.ts'))};`,resolveDir:dirname(entry),loader:'ts'},bundle:true,write:false,format:'esm',platform:'browser',loader:{'.css':'empty'},define:{'import.meta.env.VITE_WORKER_URL':'""','import.meta.env.BASE_URL':'"/"'},logLevel:'silent'});
const file=join(dir,'page.mjs');await writeFile(file,bundle.outputFiles[0].text);
class Element{
 constructor(tag='',text=''){this.tagName=tag.toUpperCase();this.text=text;this.children=[];this.attrs={};this.listeners={};this.style={};this.value='';this.disabled=false;this.validity={badInput:false};this.parentNode=null;this.classList={add:x=>this.setAttribute('class',`${this.attrs.class??''} ${x}`)};}
 setAttribute(k,v){this.attrs[k]=String(v);if(k==='value')this.value=String(v);if(k==='disabled')this.disabled=true;}getAttribute(k){return this.attrs[k]??null;}removeAttribute(k){delete this.attrs[k];}
 get dataset(){return Object.fromEntries(Object.entries(this.attrs).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5),v]));}
 appendChild(c){c.parentNode=this;this.children.push(c);if(this.tagName==='SELECT'&&c.tagName==='OPTION'&&(this.children.length===1||c.attrs.selected!==undefined))this.value=c.attrs.value??'';return c;}append(...cs){cs.forEach(c=>this.appendChild(c));}replaceChildren(...cs){this.children.forEach(c=>c.parentNode=null);this.children=[];this.text='';this.append(...cs);}remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(c=>c!==this);this.parentNode=null;}
 get firstChild(){return this.children[0]??null;}get isConnected(){return this.tagName==='BODY'||!!this.parentNode?.isConnected;}get textContent(){return this.text+this.children.map(c=>c.textContent).join('');}set textContent(s){this.replaceChildren();this.text=String(s);}
 addEventListener(t,f){(this.listeners[t]??=[]).push(f);}dispatch(t){if(t==='click'&&this.disabled)return;for(const fn of this.listeners[t]??[])fn({target:this,preventDefault(){}});}click(){this.dispatch('click');}focus(){document.activeElement=this;}
 querySelector(s){return this.querySelectorAll(s)[0]??null;}querySelectorAll(s){return walk(this).slice(1).filter(el=>{const m=s.match(/^\[([^=]+)="([^"]+)"\]$/);return m?el.attrs[m[1]]===m[2]:s.startsWith('.')?(el.attrs.class??'').split(' ').includes(s.slice(1)):el.tagName===s.toUpperCase();});}
}
const walk=n=>[n,...n.children.flatMap(walk)],cls=(n,c)=>walk(n).filter(x=>(x.attrs.class??'').split(' ').includes(c)),focus=(n,key)=>walk(n).find(x=>x.attrs['data-focus']===key),tick=()=>new Promise(r=>setImmediate(r));
const save=el=>cls(el,'tm-actions')[0].querySelector('button'),remove=(el,index)=>walk(el).find(x=>x.attrs['data-meal-index']===String(index)).querySelector('button');
const input=(el,key,value,type='input')=>{const node=focus(el,key);node.value=value;node.dispatch(type);};
const A='a'.repeat(40),B='b'.repeat(40),raw='2.0000000000000001';
const seed=()=>({schemaVersion:'3',margin:1.13,meals:[{date:'2026-09-14',mealType:'lunch',dishRef:'soup',plannedServings:8},{date:'2026-09-15',mealType:'dinner',dishRef:'stew',plannedServings:12,serviceWindow:'18:00-19:00'},{date:'2026-09-16',mealType:'lunch',dishRef:'soup'}]});
let serial=0;
async function setup({post,read,image=false}={}){
 globalThis.HTMLElement=Element;globalThis.MutationObserver=class{observe(){}disconnect(){}};const events={};globalThis.window={addEventListener:(k,f)=>(events[k]??=[]).push(f)};globalThis.location={hash:'#/admin/plan/week-a'};globalThis.document={body:new Element('body'),createElement:t=>new Element(t),createTextNode:t=>new Element('',t),activeElement:null};
 const storage=new Map();globalThis.localStorage=globalThis.sessionStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};
 const page=await import(`${pathToFileURL(file)}?case=${++serial}`),writes=[];let identity=1;
 const api=page.createTeamMealsApi('https://plan-raw-fixture.invalid',{mode:'mock',token:()=>'explicit-local-fixture',identity:()=>identity,fetch:async(url,init)=>{const u=new URL(url);if(init.method==='GET'&&read){const response=await read(u,identity);if(response)return response;}if(init.method==='POST'){const body=JSON.parse(init.body);writes.push({id:u.pathname,body});if(post)return post(body);return Response.json({ok:true,commit:B,blobSha:'after',unchanged:false,warnings:[]});}if(u.pathname==='/catalog')return Response.json({commit:u.searchParams.get('revision')??A,dishes:{soup:{schemaVersion:'3',name:{en:'Soup'},...(image?{image:{path:'soup.jpg',license:'CC0'}}:{}),components:[]},stew:{schemaVersion:'3',name:{en:'Stew'},components:[]}},ingredients:{},techniques:[],suppliers:[],translations:{machine:0,human:0,stale:0}});return Response.json({content:seed(),commit:A,blobSha:'before'});}});
 const render=page.createPlanRenderer(api),coverage=page.createPageReloadCoverage(),start=(id='week-a',lang='en')=>{document.body.replaceChildren();const el=new Element('main');document.body.append(el);const promise=render(el,{lang,planId:id,route:'admin',rest:id,setReloadCoverage:coverage.beginRender('admin',`plan/${id}`)},id);return{el,promise};},mount=async(id='week-a',lang='en')=>{const {el,promise}=start(id,lang);await promise;return el;};
 return{page,api,render,writes,mount,start,events,auth(){identity++;page.changeAuth();},async flush(){for(let i=0;i<5;i++)await tick();},cleanup(){api.dispose();document.body.replaceChildren();}};
}

test('deleting row 0 preserves the precise invalid raw text on original row 1 as remaining row 0 and blocks save',async()=>{
 const f=await setup();try{let el=await f.mount();input(el,'servings-1',raw);assert.equal(focus(el,'servings-1').value,raw);remove(el,0).click();assert.equal(focus(el,'servings-0').value,raw);assert.equal(focus(el,'servings-0').getAttribute('aria-invalid'),'true');assert.equal(save(el).disabled,true);el=await f.mount('week-a','uk');assert.equal(focus(el,'servings-0').value,raw);assert.equal(save(el).disabled,true);assert.equal(f.writes.length,0);}finally{f.cleanup();}
});
test('raw metadata is stable per document through language/plan return; read-only filters do not dirty it',async()=>{
 const f=await setup();try{let el=await f.mount();assert.equal(typeof f.render.readAuxiliary,'function');const initial=f.render.readAuxiliary('week-a');assert.equal(initial.dirty,false);input(el,'filter-date','2026-09-16','change');input(el,'range','day','change');assert.deepEqual(f.render.readAuxiliary('week-a'),initial);input(el,'range','all','change');input(el,'servings-1',raw);const edited=f.render.readAuxiliary('week-a');assert.equal(edited.dirty,true);assert.equal(edited.generation>initial.generation,true);await f.mount('week-b');assert.equal(f.render.readAuxiliary('week-a').dirty,true);assert.equal(f.render.readAuxiliary('week-b').dirty,false);el=await f.mount('week-a','uk');assert.equal(focus(el,'servings-1').value,raw);assert.deepEqual(f.render.readAuxiliary('week-a'),edited);}finally{f.cleanup();}
});
test('unapplied Add date/meal/dish survive language and plan return, and only a successful Add consumes pending',async()=>{
 const f=await setup();try{let el=await f.mount();input(el,'add-date','2026-10-03');input(el,'add-meal','dinner','change');input(el,'add-dish','stew','change');el=await f.mount('week-a','uk');assert.equal(focus(el,'add-date').value,'2026-10-03');assert.equal(focus(el,'add-meal').value,'dinner');assert.equal(focus(el,'add-dish').value,'stew');assert.equal(f.render.readAuxiliary('week-a').dirty,true);await f.mount('week-b');el=await f.mount();assert.equal(focus(el,'add-date').value,'2026-10-03');input(el,'add-date','');cls(el,'tm-add-form')[0].dispatch('submit');assert.equal(f.render.readAuxiliary('week-a').dirty,true);assert.equal(walk(el).filter(x=>x.attrs['data-meal-index']!==undefined).length,3);input(el,'add-date','2026-10-03');cls(el,'tm-add-form')[0].dispatch('submit');assert.equal(f.render.readAuxiliary('week-a').dirty,false);save(el).click();await f.flush();assert.equal(f.writes.length,1);assert.deepEqual(f.writes[0].body.meals[3],{date:'2026-10-03',mealType:'dinner',dishRef:'stew'});}finally{f.cleanup();}
});

test('removal shifts only later raw indices, preserves earlier ones, and consumes only the explicitly removed row',async()=>{
 const f=await setup();try{const el=await f.mount();input(el,'servings-0','1.5');input(el,'servings-1',raw);input(el,'servings-2','9007199254740993');remove(el,1).click();assert.equal(focus(el,'servings-0').value,'1.5');assert.equal(focus(el,'servings-1').value,'9007199254740993');assert.equal(f.render.readAuxiliary('week-a').dirty,true);input(el,'servings-0','4');assert.equal(f.render.readAuxiliary('week-a').dirty,true);remove(el,1).click();assert.equal(f.render.readAuxiliary('week-a').dirty,false);save(el).click();await f.flush();assert.deepEqual(f.writes[0].body.meals,[{date:'2026-09-14',mealType:'lunch',dishRef:'soup',plannedServings:4}]);assert.equal(f.writes[0].body.margin,1.13);}finally{f.cleanup();}
});
test('unrelated later row removal never consumes an earlier invalid raw value',async()=>{
 const f=await setup();try{const el=await f.mount();input(el,'servings-0',raw);const before=f.render.readAuxiliary('week-a');remove(el,2).click();assert.equal(focus(el,'servings-0').value,raw);assert.equal(save(el).disabled,true);assert.deepEqual(f.render.readAuxiliary('week-a'),before);}finally{f.cleanup();}
});
test('stale Add/Remove handlers cannot consume the prior document raw buffer after changing plans',async()=>{
 const f=await setup();try{let el=await f.mount();input(el,'servings-1',raw);input(el,'add-dish','stew','change');const oldRemove=remove(el,0),oldAdd=cls(el,'tm-add-form')[0],before=f.render.readAuxiliary('week-a');await f.mount('week-b');oldRemove.click();oldAdd.dispatch('submit');assert.deepEqual(f.render.readAuxiliary('week-a'),before);el=await f.mount();assert.equal(focus(el,'servings-1').value,raw);assert.equal(focus(el,'add-dish').value,'stew');assert.equal(walk(el).filter(x=>x.attrs['data-meal-index']!==undefined).length,3);}finally{f.cleanup();}
});
test('saving existing JSON does not consume unapplied Add choices, including unknown result and route return',async()=>{
 const f=await setup({post:async()=>{throw new Error('lost response');}});try{let el=await f.mount();input(el,'servings-0','9');input(el,'add-date','2026-10-03');input(el,'add-dish','stew','change');const before=f.render.readAuxiliary('week-a');save(el).click();await f.flush();assert.equal(f.writes.length,1);assert.equal(f.writes[0].body.meals.length,3);assert.deepEqual(f.render.readAuxiliary('week-a'),before);await f.mount('week-b');el=await f.mount('week-a','uk');assert.equal(focus(el,'add-date').value,'2026-10-03');assert.equal(focus(el,'add-dish').value,'stew');assert.equal(f.render.readAuxiliary('week-a').dirty,true);assert.equal(walk(el).some(x=>x.attrs['data-phase']==='outcome-unknown'),true);}finally{f.cleanup();}
});
test('acknowledging an earlier save does not erase newer invalid input; correcting it serializes only through C1',async()=>{
 let release;const f=await setup({post:()=>new Promise(r=>release=r)});try{let el=await f.mount();input(el,'servings-0','9');save(el).click();await f.flush();input(el,'servings-1',raw);const before=f.render.readAuxiliary('week-a');release(Response.json({ok:true,commit:B,blobSha:'after',unchanged:false,warnings:[]}));await f.flush();assert.equal(focus(el,'servings-1').value,raw);const after=f.render.readAuxiliary('week-a');assert.deepEqual({...after,generation:before.generation},before);assert(after.generation>before.generation,'the acknowledged source causes a new catalog read with its own generation');assert.equal(save(el).disabled,true);el=await f.mount('week-a','zh');input(el,'servings-1','13');assert.equal(f.render.readAuxiliary('week-a').dirty,false);assert.equal(save(el).disabled,false);assert.equal(f.writes[0].body.meals[1].plannedServings,12);}finally{f.cleanup();}
});
test('Add defaults are clean, reverting an input makes it clean with newer generation, and successful Add does not leave a false pending flag',async()=>{
 const f=await setup();try{const el=await f.mount(),initial=f.render.readAuxiliary('week-a'),date=focus(el,'add-date').value;assert.equal(f.render.readAuxiliary('unvisited'),null);input(el,'add-date','2026-10-03');input(el,'add-date',date);const reverted=f.render.readAuxiliary('week-a');assert.equal(reverted.dirty,false);assert.equal(reverted.generation>initial.generation,true);input(el,'add-dish','stew','change');cls(el,'tm-add-form')[0].dispatch('submit');const consumed=f.render.readAuxiliary('week-a');assert.equal(consumed.dirty,false);assert.equal(consumed.ownerId,initial.ownerId);assert.equal(consumed.identity.id,'week-a');assert(Object.isFrozen(consumed));assert(Object.isFrozen(consumed.identity));assert.equal(f.writes.length,0);}finally{f.cleanup();}
});

test('clean C1 JSON with pending raw input is visibly unsaved without changing the C1 phase or document',async()=>{
 const f=await setup();try{const el=await f.mount();input(el,'add-dish','stew','change');assert.match(el.textContent,/Unsaved changes/);assert.doesNotMatch(el.textContent,/Loaded; unchanged/);assert.equal(walk(el).some(x=>x.attrs['data-phase']==='clean'),true);assert.equal(f.render.readAuxiliary('week-a').dirty,true);assert.equal(f.writes.length,0);}finally{f.cleanup();}
});


test('registered raw Plan input protects offscreen updates while C1 stays the only JSON owner',async()=>{
 const f=await setup();try{let el=await f.mount();assert.equal(f.page.inspectReloadSafety().reason,'clear');input(el,'add-dish','stew','change');let snapshot=f.page.inspectReloadSafety();assert.equal(snapshot.reason,'dirty');assert(snapshot.records.some(r=>r.kind==='plan'&&r.id==='week-a'&&r.dirty&&r.ownerId.startsWith('auxiliary-')));await f.mount('week-b');assert.equal(f.page.inspectReloadSafety().reason,'dirty');el=await f.mount();input(el,'add-dish','','change');assert.equal(f.page.inspectReloadSafety().reason,'clear');}finally{f.cleanup();}
});
test('initial Source and catalog reads each register before awaiting and finish their original coverage',async()=>{
 let release;const f=await setup({read:u=>u.pathname.startsWith('/source/plan')?new Promise(r=>release=r):undefined});try{const pending=f.start();await f.flush();assert.equal(f.page.inspectReloadSafety().reason,'saving');assert(f.page.inspectReloadSafety().records.some(r=>r.ownerId.startsWith('auxiliary-')&&r.phase==='busy'));release(Response.json({content:seed(),commit:A,blobSha:'before'}));await pending.promise;assert.equal(f.page.inspectReloadSafety().reason,'clear');assert.equal(f.render.readAuxiliary('week-a').phase,'idle');}finally{f.cleanup();}
});
test('old initialization result closes only old scope while B same-page read remains protected',async()=>{
 const releases=new Map();const f=await setup({read:(u,identity)=>u.pathname.startsWith('/source/plan')?new Promise(r=>releases.set(identity,r)):undefined});try{const a=f.start('private-plan-a');await f.flush();f.auth();const b=f.start('private-plan-a','uk');await f.flush();const before=f.page.inspectReloadSafety();assert.equal(before.reason,'unknown');assert(before.records.some(r=>r.ownerId.startsWith('previous-page-')));releases.get(1)(Response.json({content:seed(),commit:A,blobSha:'old'}));await a.promise;const during=f.page.inspectReloadSafety();assert.equal(during.reason,'saving');assert(during.records.some(r=>r.phase==='untracked'));releases.get(2)(Response.json({content:seed(),commit:A,blobSha:'new'}));await b.promise;assert.equal(f.page.inspectReloadSafety().reason,'clear');assert.equal(focus(b.el,'servings-0').value,'8');}finally{f.cleanup();}
});
test('a known Source error releases its read and page coverage without clearing existing raw input',async()=>{
 let fail=true;const f=await setup({read:u=>u.pathname.startsWith('/source/plan')&&fail?Response.json({ok:false,errors:[{path:'',code:'upstream_unavailable',message:''}]},{status:503}):undefined});try{const el=await f.mount();assert.equal(f.page.inspectReloadSafety().reason,'clear');fail=false;walk(el).find(e=>e.tagName==='BUTTON'&&e.textContent==='Read again').click();await f.flush();input(el,'servings-1',raw);assert.equal(f.page.inspectReloadSafety().reason,'dirty');}finally{f.cleanup();}
});

// Reference-v3 presentation: these checks use the existing renderer and real TeamMealsApi.
test('compact Plan keeps three direct count inputs, day navigation and first-screen actions ahead of secondary editing',async()=>{
 const f=await setup();try{const el=await f.mount();assert.equal(cls(el,'tm-plan').length,1);assert.equal(cls(el,'tm-plan-day').length,7);assert.equal(cls(el,'tm-plan-row-main').length,3);assert.equal(focus(el,'servings-2').value,'');assert.equal(cls(el,'tm-plan-edit').length,3);const nodes=walk(el);assert(nodes.indexOf(cls(el,'tm-actions')[0])<nodes.indexOf(cls(el,'tm-add-form')[0]));const before=f.render.readAuxiliary('week-a');cls(el,'tm-plan-day')[1].click();assert.equal(cls(el,'tm-plan-row-main').length,1);assert.equal(focus(el,'servings-1').value,'12');assert.deepEqual(f.render.readAuxiliary('week-a'),before);assert.equal(f.writes.length,0);}finally{f.cleanup();}
});
test('controlled Plan images use the bound catalog revision with a real read ticket; late images cannot paint the next page',async()=>{
 let release;const calls=[];const f=await setup({image:true,read:u=>{if(u.pathname==='/asset'){calls.push(u);return new Promise(r=>release=r);}}});try{const el=await f.mount();await f.flush();assert.equal(calls.length,1);assert.equal(calls[0].searchParams.get('revision'),A);assert.equal(calls[0].searchParams.get('owner'),'data/dishes/soup.json');assert.equal(calls[0].searchParams.get('pointer'),'/image');assert.equal(f.render.readAuxiliary('week-a').phase,'busy');document.body.replaceChildren();release(new Response('image',{headers:{'Content-Type':'image/png','X-Source-Revision':A}}));await f.flush();assert.equal(el.querySelectorAll('img').length,0);assert.equal(f.render.readAuxiliary('week-a').phase,'idle');assert.equal(f.writes.length,0);}finally{f.cleanup();}
});
test('same-revision thumbnails survive a language rebind without overwriting raw counts or duplicating HTTP reads',async()=>{
 let release;let reads=0;const f=await setup({image:true,read:u=>u.pathname==='/asset'?(reads++,new Promise(r=>release=r)):undefined});try{let el=await f.mount();input(el,'servings-0',raw);const old=el;el=await f.mount('week-a','uk');release(new Response('image',{headers:{'Content-Type':'image/png','X-Source-Revision':A}}));await f.flush();assert.equal(reads,1);assert.equal(old.querySelectorAll('img').length,0);assert.equal(el.querySelectorAll('img').length,2);assert.match(el.querySelector('img').getAttribute('src'),/^blob:/);assert.equal(focus(el,'servings-0').value,raw);assert.equal(focus(el,'servings-2').value,'');assert.equal(save(el).disabled,true);assert.equal(f.render.readAuxiliary('week-a').phase,'idle');assert.equal(f.writes.length,0);}finally{f.cleanup();}
});
for(const kind of ['unavailable','wrong-revision'])test(`${kind}: a thumbnail failure is visible and releases its read without disabling ordinary Plan editing`,async()=>{
 const f=await setup({image:true,read:u=>u.pathname==='/asset'?(kind==='unavailable'?Response.json({ok:false,errors:[{code:'upstream_unavailable',path:'',message:''}]},{status:503}):new Response('image',{headers:{'Content-Type':'image/png','X-Source-Revision':B}})):undefined});try{const el=await f.mount();await f.flush();assert.equal(el.querySelectorAll('img').length,0);assert.equal(cls(el,'tm-plan-photo')[0].getAttribute('aria-label'),'Image unavailable');assert.equal(f.render.readAuxiliary('week-a').phase,'idle');input(el,'servings-0','9');assert.equal(save(el).disabled,false);save(el).click();await f.flush();assert.equal(f.writes.length,1);assert.equal(f.writes[0].body.meals[0].plannedServings,9);assert.equal(Object.hasOwn(f.writes[0].body.meals[2],'plannedServings'),false);}finally{f.cleanup();}
});
test('selecting another day moves a clean Add default to that day before directly adding a dish',async()=>{
 const f=await setup();try{const el=await f.mount();cls(el,'tm-plan-day')[1].click();assert.equal(focus(el,'add-date').value,'2026-09-15');assert.equal(f.render.readAuxiliary('week-a').dirty,false);input(el,'add-dish','soup','change');cls(el,'tm-add-form')[0].dispatch('submit');save(el).click();await f.flush();assert.equal(f.writes[0].body.meals.at(-1).date,'2026-09-15');assert.equal(Object.hasOwn(f.writes[0].body.meals.at(-1),'plannedServings'),false);}finally{f.cleanup();}
});
test('selecting another day preserves pending Add inputs and visibly identifies their destination',async()=>{
 const f=await setup();try{const el=await f.mount();input(el,'add-date','2026-10-03');input(el,'add-dish','soup','change');cls(el,'tm-plan-day')[1].click();assert.equal(focus(el,'add-date').value,'2026-10-03');assert.equal(focus(el,'add-dish').value,'soup');assert.equal(f.render.readAuxiliary('week-a').dirty,true);assert.match(walk(el).find(n=>n.attrs['data-plan-raw-pending']==='true').textContent,/2026-10-03.*Lunch/);assert.equal(f.writes.length,0);}finally{f.cleanup();}
});
test('retired-auth image completion settles its own ticket while the new identity image read stays busy',async()=>{
 const releases=new Map();const f=await setup({image:true,read:(u,identity)=>u.pathname==='/asset'?new Promise(r=>releases.set(identity,r)):undefined});try{const old=await f.mount();await f.flush();f.auth();const current=await f.mount('week-a','uk');await f.flush();assert.equal(releases.size,2);releases.get(1)(new Response('old image',{headers:{'Content-Type':'image/png','X-Source-Revision':A}}));await f.flush();assert.equal(old.querySelectorAll('img').length,0);assert.equal(current.querySelectorAll('img').length,0);assert.equal(f.render.readAuxiliary('week-a').phase,'busy');releases.get(2)(new Response('current image',{headers:{'Content-Type':'image/png','X-Source-Revision':A}}));await f.flush();assert.equal(current.querySelectorAll('img').length,2);assert.equal(f.render.readAuxiliary('week-a').phase,'idle');assert.equal(f.writes.length,0);}finally{f.cleanup();}
});
