import '../src/tokens.css'; import '../src/styles.css';
import {render} from '../src/pages/admin/import';
import {createTeamMealsApi} from '../src/api/team-meals';
import {clearDraftPlan,getDraftPlan} from '../src/admin/store';
const app=document.querySelector('#app')!,out=document.querySelector('#result')!,sha='a'.repeat(40);
const catalog={commit:sha,dishes:{soup:{schemaVersion:'3',name:{zh:'原汤',en:'Soup',uk:'Суп'},status:'active',components:[{ingredientRef:'salt'}]}},ingredients:{},techniques:[],suppliers:[],translations:{machine:0,human:0,stale:0}};
const checks:any[]=[],requests:any[]=[];let api:any,principal=1,gate:any=null;
const tick=()=>new Promise(r=>setTimeout(r,35));
const $=(s:string)=>app.querySelector(s) as HTMLInputElement;
async function paint(id='week-38',lang='en'){const el=document.createElement('section');app.replaceChildren(el);await render(el,{lang,route:'admin',rest:id,planId:id,data:{},t:(x:string)=>x}as any,id,api);}
function type(s:string,value:string){const e=$(s);e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}));}
function parse(text='周一午 原汤 8'){type('#adm-import-text',text);$('.adm-import-parse').click();}
async function reset(){api?.dispose();clearDraftPlan('week-38');principal=1;gate=null;api=createTeamMealsApi('https://import-owner-fixture.invalid',{mode:'mock',identity:()=>principal,token:()=>`mock-${principal}`,fetch:async(url,init)=>{const path=new URL(url).pathname;requests.push({method:init.method,path});if(init.method!=='GET')throw new Error('Remote writes forbidden');if(path==='/catalog')return Response.json(catalog);if(path.startsWith('/source/plan/')){if(gate)await gate;return Response.json({commit:sha,blobSha:'original',content:{schemaVersion:'3',meals:[{date:'2026-09-14',mealType:'lunch',dishRef:'soup',plannedServings:8}]}});}throw new Error('Unexpected read');}});await paint();}
function file(name:string,count=8){let release:any,reject:any;const text=`date,meal,dish,servings\nMon,lunch,原汤,${count}`,blob=new File([text],name,{type:'text/csv'}),promise=new Promise<ArrayBuffer>((ok,no)=>{release=()=>ok(new TextEncoder().encode(text).buffer);reject=no;});Object.defineProperty(blob,'arrayBuffer',{value:()=>promise});return {blob,release,reject};}
function choose(f:File){const transfer=new DataTransfer();transfer.items.add(f);$('#adm-import-file').files=transfer.files;$('#adm-import-file').dispatchEvent(new Event('change',{bubbles:true}));}
function check(name:string,pass:boolean,detail:any={}){checks.push({name,pass:!!pass,detail});out.textContent=JSON.stringify({checks,requests},null,2);}
async function run(){checks.length=0;requests.length=0;(document.querySelector('#run')as HTMLButtonElement).disabled=true;
try{
 await reset();parse();type('.adm-import-servings','2.0000000000000001');await paint('week-39');type('#adm-import-text','other week raw');await paint('week-38','uk');check('raw and invalid servings return to original plan',$('#adm-import-text').value==='周一午 原汤 8'&&$('.adm-import-servings')?.value==='2.0000000000000001'&&$('.adm-import-submit')?.disabled);await paint('week-39');check('other plan retains own raw',$('#adm-import-text').value==='other week raw');
 for(const detour of ['language','plan']){await reset();parse();const f=file(`${detour}.csv`);choose(f.blob);await paint(detour==='plan'?'week-39':'week-38','uk');f.release();await tick();if(detour==='plan'){check('late file never enters other plan',!$('.adm-import-servings'));await paint();}check(`CSV survives ${detour}`,app.textContent!.includes(`${detour}.csv`)&&$('.adm-import-servings')?.value==='8');}
 await reset();parse();const old=file('old.csv',3),fresh=file('new.csv',9);choose(old.blob);await paint('week-38','uk');choose(fresh.blob);fresh.release();await tick();old.release();await tick();check('new file wins',app.textContent!.includes('new.csv')&&$('.adm-import-servings')?.value==='9');const last=file('late.csv',99);choose(last.blob);parse('周一午 原汤 6');last.release();await tick();check('new paste wins',$('.adm-import-servings')?.value==='6');
 await reset();parse();let release:any;gate=new Promise(r=>release=r);$('.adm-import-submit').click();await tick();await paint('week-38','uk');const before=requests.filter(r=>r.path.startsWith('/source/')).length;check('Source busy survives language',$('.adm-import-submit').disabled);$('.adm-import-submit').click();await tick();check('pending Source action cannot duplicate',requests.filter(r=>r.path.startsWith('/source/')).length===before);type('.adm-import-servings','1.5');gate=null;release();await tick();check('canceled action keeps invalid raw and no draft',getDraftPlan('week-38')===null&&$('.adm-import-servings').value==='1.5'&&$('.adm-import-submit').disabled);
 await reset();parse();const broken=file('broken.csv');choose(broken.blob);await paint('week-38','en');broken.reject(new Error('test local failure'));await tick();check('file error survives repaint',app.textContent!.includes("Couldn't read the file"));const privateFile=file('private.csv');choose(privateFile.blob);principal++;await paint();privateFile.release();await tick();check('old auth file cannot enter new owner',$('#adm-import-text').value===''&&!$('.adm-import-servings')&&!app.textContent!.includes('private.csv'));
 check('all requests read-only',requests.every(r=>r.method==='GET'));
}catch(error){check('fixture completes',false,String(error));}finally{out.textContent=JSON.stringify({summary:`${checks.filter(c=>c.pass).length}/${checks.length}`,checks,requests},null,2);(document.querySelector('#run')as HTMLButtonElement).disabled=false;}}
document.querySelector('#run')!.addEventListener('click',()=>void run());
