// Author reproduction of the independent 7c61737 browser probes; original 12 assertions retained.
import '../src/tokens.css';import '../src/styles.css';import {renderFrozenPrep} from '../src/pages/prep.ts';import {renderFrozenMenu} from '../src/pages/menu.ts';import {createTeamMealsViewModel} from '../src/view-models/team-meals.ts';
const A='a'.repeat(40),B='b'.repeat(40),clone=x=>structuredClone(x),image={src:'https://must-not-fetch.invalid/same.svg',license:'CC BY 4.0',author:'Author',sourceUrl:'javascript:alert(1)'};
const input={menuPlans:{week:{schemaVersion:'3',meals:[{date:'2026-09-14',mealType:'lunch',dishRef:'soup'},{date:'2026-09-14',mealType:'lunch',dishRef:'other',plannedServings:3},{date:'2026-09-14',mealType:'dinner',dishRef:'soup',plannedServings:7},{date:'2026-09-15',mealType:'dinner',dishRef:'missing-dish'}]}},dishes:{soup:{schemaVersion:'3',name:{zh:'汤',en:'Soup',uk:'Суп'},status:'draft',image,components:[{ingredientRef:'tomato',qty:{value:1500,unit:'g'},prep:{techniqueRef:'mix',image,size:'2 cm',timing:'morning',note:{zh:'原注',en:'Original note',uk:'Примітка'}}},{ingredientRef:'tomato'},{ingredientRef:'salt',qty:{unit:'to-taste'}},{ingredientRef:'missing'}],steps:[{text:{zh:'第一步',en:'First step',uk:'Перший крок'},techniqueRef:'mix',image,clip:{videoUrl:'https://example.org/video',start:3,end:9}},{text:{zh:'第二步',en:'Second step',uk:'Другий крок'},clip:{videoUrl:'javascript:alert(1)',start:10,end:13}}],provenance:{source:'video',videoUrl:'https://example.org/video'}},other:{schemaVersion:'2',name:{zh:'另一道',en:'Other dish'},baseServings:50,status:'active',components:[{ingredientRef:'tomato',qty:{value:2,unit:'kg'}}],steps:[{text:{en:'Other unique step'}}]}},ingredients:{tomato:{schemaVersion:'2',name:{zh:'番茄',en:'Tomato',uk:'Помідор'},role:'main',baseUnit:'g'},salt:{schemaVersion:'2',name:{zh:'盐',en:'Salt',uk:'Сіль'},role:'seasoning',baseUnit:'g'}},techniques:[{id:'unused',kind:'pretreat',name:{en:'Unused'},image},{id:'mix',kind:'pretreat',name:{zh:'拌',en:'Mix',uk:'Змішати'},note:{en:'Catalog note'},image}]};
const selection=[{menuPlanRef:'week',date:'2026-09-14',mealType:'lunch'},{menuPlanRef:'week',date:'2026-09-14',mealType:'dinner'},{menuPlanRef:'week',date:'2026-09-15',mealType:'dinner'},{menuPlanRef:'week',date:'2026-09-16',mealType:'lunch'}];
const vm=createTeamMealsViewModel({mode:'mock',sessionKey:()=>0,getCatalog:async()=>({commit:A,...clone(input),suppliers:[],translations:{}}),getPlan:async()=>({content:clone(input.menuPlans.week),commit:A,blobSha:'mock-only'})});
const source=await vm.loadSaved({revision:A,selection,at:'2026-09-11T00:00:00Z'});
const main=document.querySelector('#main')!,out=document.querySelector('#result')!,button=document.querySelector('#run')!,checks=[],calls=[],created=[],revoked=[];
const create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=blob=>{const url=create(blob);created.push(url);return url;};URL.revokeObjectURL=url=>{revoked.push(url);revoke(url);};
const svg=new Blob(['<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12"><rect width="12" height="12" fill="green"/></svg>'],{type:'image/svg+xml'});
let stop=()=>{};const pause=()=>new Promise(r=>setTimeout(r,30));const asset=async q=>{calls.push(q);return{bytes:svg,sourceRevision:A};},techniqueAsset=async id=>{calls.push({techniqueRef:id});return{bytes:svg,sourceRevision:A};};
const report=(name,pass,detail='')=>{checks.push({name,pass:!!pass,detail});out.textContent=JSON.stringify({checks,calls},null,2);};
function prep(opts={}){stop();stop=renderFrozenPrep(main,source,{lang:'en',asset,techniqueAsset,...opts});}
function menu(opts={}){stop();stop=renderFrozenMenu(main,source,{lang:'en',asset,techniqueAsset,...opts});}
const row={menuPlanRef:'week',mealIndex:0,date:'2026-09-14',mealType:'lunch'};
async function run(){button.disabled=true;checks.length=0;calls.length=0;created.length=0;revoked.length=0;const original=JSON.stringify(source);
try{
 menu({selection:{date:'2026-09-14'}});report('all repeated meal occurrences stay separate',main.querySelectorAll('[data-menu-plan]').length===3&&main.textContent.includes('Tomato · Tomato · Salt · missing'));
 const panel=main.querySelectorAll('[data-menu-plan] > details')[1];panel.open=true;await pause();report('second meal expansion uses its original row only',panel.textContent.includes('Other unique step')&&!panel.textContent.includes('First step'));
 prep({selection:row});await pause();await pause();report('all original components and complete steps',main.querySelectorAll('[data-component-index]').length===4&&main.querySelectorAll('[data-step-index]').length===2&&main.textContent.includes('1500 g')&&main.textContent.includes('Quantity not recorded')&&main.textContent.includes('To taste'));
 report('optional counts stay unrecorded without default scaling',main.textContent.includes('Planned servings: Not recorded')&&main.textContent.includes('Original recipe servings: Not recorded'));
 report('same image source uses explicit technique IDs and exact JSON pointers',calls.filter(x=>x.techniqueRef==='mix').length===2&&calls.some(x=>x.owner==='data/dishes/soup.json'&&x.pointer==='/components/0/prep/image')&&calls.some(x=>x.owner==='data/dishes/soup.json'&&x.pointer==='/steps/0/image')&&calls.filter(x=>x.revision).every(x=>x.revision===A));
 report('real browser renders only Blob images and safe external links',main.querySelectorAll('img').length===5&&[...main.querySelectorAll('img')].every(x=>x.src.startsWith('blob:'))&&![...main.querySelectorAll('a')].some(x=>x.href.startsWith('javascript:')));
 const oldUrls=[...created];prep({lang:'uk',selection:row,asset:async()=>({bytes:svg,sourceRevision:B}),techniqueAsset:async()=>({bytes:svg,sourceRevision:B})});await pause();report('same host language repaint revokes old and rejects wrong version',oldUrls.every(u=>revoked.includes(u))&&!main.querySelector('img')&&main.textContent.includes('Перший крок'));
 let release;const pending=new Promise(r=>release=r);prep({selection:row,asset:()=>pending,techniqueAsset:()=>pending});await pause();const old=main.firstElementChild;prep({lang:'zh',selection:{menuPlanRef:'week',mealIndex:1}});release({bytes:svg,sourceRevision:A});await pause();report('late previous recipe images cannot fill later selection',!old.querySelector('img')&&main.textContent.includes('Other unique step')&&!main.textContent.includes('First step'));
 const host=document.createElement('div');main.append(host);let finish;const held=new Promise(r=>finish=r);renderFrozenPrep(host,source,{lang:'en',selection:row,asset:()=>held,techniqueAsset:()=>held});await pause();host.remove();await pause();const before=created.length;finish({bytes:svg,sourceRevision:A});await pause();report('detached host has no late object URL creation',created.length===before);
 prep({selection:{menuPlanRef:'week',date:'2026-09-16',mealType:'lunch'}});const prepEmpty=main.textContent;report('empty selected slot is not mislabeled missing from another date',prepEmpty.includes('No dishes in the selected meal')&&prepEmpty.includes('No recorded meals in this selection')&&!prepEmpty.includes('Record unavailable'),prepEmpty);
 menu({selection:{menuPlanRef:'week',date:'2026-09-16',mealType:'lunch'}});report('menu empty slot is independent of unrelated missing recipe',main.textContent.includes('No recorded meals in this selection')&&!main.textContent.includes('Some source records are unavailable'),main.textContent);
 for(const [name,render] of [['prep',prep],['menu',menu]]){
   render({selection:{menuPlanRef:'week',date:'2026-09-15',mealType:'dinner'}});
   report(`${name}: selected missing dish retains its original reference and notice`,main.querySelectorAll('[data-source-issue="missing-dish"]').length===1&&main.textContent.includes('missing-dish')&&main.textContent.includes(name==='prep'?'Record unavailable':'Recipe unavailable')&&!main.textContent.includes('No recorded meals in this selection'),main.textContent);
 }
 report('source bytes remain unchanged',JSON.stringify(source)===original);
}catch(e){report('probe exception',false,e.message);}finally{out.textContent=JSON.stringify({summary:`${checks.filter(x=>x.pass).length}/${checks.length}`,checks,calls},null,2);button.disabled=false;}}
button.addEventListener('click',()=>void run());

document.querySelector('#show')!.addEventListener('click',()=>{
 const lang=(document.querySelector('#lang') as HTMLSelectElement).value;
 const page=(document.querySelector('#page') as HTMLSelectElement).value;
 const missing=(document.querySelector('#scope') as HTMLSelectElement).value==='missing';
 (page==='prep'?prep:menu)({lang,selection:{menuPlanRef:'week',date:missing?'2026-09-15':'2026-09-16',mealType:missing?'dinner':'lunch'}});
});
