import '../src/tokens.css';import '../src/styles.css';import {render} from '../src/pages/admin/import.ts';import {createTeamMealsApi} from '../src/api/team-meals.ts';import {bindDraftStore} from '../src/admin/store.ts';import {createPlanRenderer} from '../src/pages/admin/plan.ts';import {render as renderIngredient} from '../src/pages/admin/ingredient-new.ts';
const id='week-38',A='a'.repeat(40),catalog={commit:A,dishes:{soup:{schemaVersion:'3',name:{zh:'原汤',en:'Soup',uk:'Суп'},status:'active',components:[{ingredientRef:'salt'}]},other:{schemaVersion:'2',name:{zh:'另一道',en:'Other'},status:'active'}},ingredients:{},techniques:[],suppliers:[],translations:{machine:0,human:0,stale:0}};
const saved={schemaVersion:'3',name:{zh:'private-A-plan'},margin:1.17,meals:[{date:'2026-09-14',mealType:'lunch',dishRef:'soup',plannedServings:8,serviceWindow:'12:00-13:00'},{date:'2026-09-14',mealType:'lunch',dishRef:'soup',plannedServings:11},{date:'2026-09-17',mealType:'dinner',dishRef:'other',plannedServings:19}]};
let api,drafts,planRenderer,principal=1,lang='en',fail='',hold=false,release,requests=[];const checks=[],app=document.querySelector('#app')!,out=document.querySelector('#result')!;
function connect(){api?.dispose();api=createTeamMealsApi('https://independent-import.invalid',{mode:'mock',token:()=>`local-${principal}`,identity:()=>principal,fetch:async(url,init)=>{const path=new URL(url).pathname;requests.push({principal,method:init.method,path});if(init.method!=='GET')throw new Error('No writes permitted');if(path==='/catalog')return Response.json(catalog);if(path===`/source/plan/${id}`){if(hold)await new Promise(r=>release=r);if(fail)return Response.json({ok:false,errors:[{path:'',code:fail==='404'?'not_found':'forbidden',message:fail}]},{status:Number(fail)});return Response.json({content:principal===1?saved:{schemaVersion:'3',name:{zh:'B-plan'},margin:9,meals:[]},commit:A,blobSha:'source-'+principal});}throw new Error('Unexpected read');}});planRenderer=createPlanRenderer(api);}
async function paint(){const el=document.createElement('section');app.replaceChildren(el);await render(el,{lang,rest:id,route:'admin',planId:id,data:{},t:x=>x},id,api);drafts=bindDraftStore(api);}
async function reset(){principal=1;lang='en';fail='';hold=false;release=null;requests=[];connect();await paint();}
const pause=()=>new Promise(r=>setTimeout(r,25));async function until(fn,msg){for(let i=0;i<120;i++){if(fn())return;await pause();}throw new Error(msg);}
const $=s=>app.querySelector(s),check=(name,pass,detail='')=>{checks.push({name,pass:!!pass,detail});out.textContent=JSON.stringify({checks,requests},null,2);};
function input(sel,value){const el=$(sel);el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}));}
function parse(text){input('#adm-import-text',text);$('.adm-import-parse').click();}
async function importNow(){$('.adm-import-submit').click();await until(()=>!!drafts.getDraftPlan(id),'draft expected');return drafts.getDraftPlan(id);}
async function caseOf(name,work){try{await work();}catch(e){check(name,false,e.message);}}
async function run(){checks.length=0;(document.querySelector('#run')as HTMLButtonElement).disabled=true;
await caseOf('CSV',async()=>{await reset();const file=new File(['date,meal,dish,servings\n2026-09-14,lunch,原汤,\n2026-09-15,dinner,另一道,\n'],'local.csv',{type:'text/csv'}),dt=new DataTransfer();dt.items.add(file);$('#adm-import-file').files=dt.files;$('#adm-import-file').dispatchEvent(new Event('change',{bubbles:true}));await until(()=>app.querySelectorAll('.adm-import-servings').length===2,'CSV rows');check('CSV absent counts stay blank',Array.from(app.querySelectorAll('.adm-import-servings')).every(x=>x.value===''));const p=await importNow();check('CSV keeps prior duplicate counts and absent new count',p.meals.filter(x=>x.dishRef==='soup').map(x=>x.plannedServings).join(',')==='8,11'&&!Object.hasOwn(p.meals.find(x=>x.date==='2026-09-15'),'plannedServings'));});
await caseOf('source failure',async()=>{await reset();parse('周一午 原汤');fail='403';$('.adm-import-submit').click();await pause();await pause();check('Source 403 cannot create an empty-base draft',drafts.getDraftPlan(id)===null&&!!app.querySelector('[role="alert"]'));fail='404';const p=await importNow();check('confirmed Source 404 alone creates v3 unknown count',p.schemaVersion==='3'&&p.meals.length===1&&!Object.hasOwn(p.meals[0],'plannedServings'));});
await caseOf('late language',async()=>{await reset();parse('周一午 原汤 8');hold=true;$('.adm-import-submit').click();await until(()=>!!release,'held read');lang='uk';await paint();input('.adm-import-servings','6');hold=false;release();await pause();check('language rebind ignores old saved-plan completion',drafts.getDraftPlan(id)===null&&$('.adm-import-servings').value==='6');});
await caseOf('invalid after await',async()=>{await reset();parse('周一午 原汤 8');hold=true;$('.adm-import-submit').click();await until(()=>!!release,'held read');input('.adm-import-servings','1.5');hold=false;release();await pause();check('invalid late preview stays blocked after canceled import',drafts.getDraftPlan(id)===null&&$('.adm-import-servings').getAttribute('aria-invalid')==='true'&&$('.adm-import-submit').disabled,JSON.stringify({draft:drafts.getDraftPlan(id),invalid:$('.adm-import-servings').getAttribute('aria-invalid'),disabled:$('.adm-import-submit').disabled,button:$('.adm-import-submit').textContent}));});
await caseOf('auth draft',async()=>{await reset();parse('周一午 原汤');await importNow();principal=2;lang='uk';await paint();check('new auth does not display old imported draft notice',!app.textContent.includes('імпортовано')&&!app.querySelector('.adm-notice-action'),app.textContent.slice(0,400));parse('周二晚 另一道');const p=await importNow();check('new-auth import uses its own source rather than old shared draft',p.name?.zh==='B-plan'&&p.margin===9&&!p.meals.some(x=>x.plannedServings===19),JSON.stringify({plan:p,requests}));});

await caseOf('same auth Plan composition',async()=>{await reset();parse('周一午 原汤 6');await importNow();const planEl=document.createElement('section');app.replaceChildren(planEl);await planRenderer(planEl,{lang:'en',rest:id,route:'admin',planId:id,data:{},t:x=>x},id);check('Import draft enters Plan with supplied count and complete duplicate rows',app.querySelector('[data-focus="servings-0"]')?.value==='6'&&app.querySelector('[data-focus="servings-1"]')?.value==='11'&&app.querySelector('[data-focus="servings-2"]')?.value==='19');lang='uk';await paint();check('Import raw survives Plan return in same authentication',$('#adm-import-text').value==='周一午 原汤 6');const back=document.createElement('section');app.replaceChildren(back);await planRenderer(back,{lang:'uk',rest:id,route:'admin',planId:id,data:{},t:x=>x},id);check('Plan C1 draft survives Import round trip without another write',app.querySelector('[data-focus="servings-0"]')?.value==='6'&&requests.every(r=>r.method==='GET'));});
await caseOf('old late Source and handle',async()=>{await reset();parse('周一午 原汤 8');hold=true;$('.adm-import-submit').click();await until(()=>!!release,'A pending');const a=drafts;principal=2;await paint();const b=drafts,expected={schemaVersion:'3',name:{zh:'B-owned'},meals:[]};b.setDraftPlan(id,expected,'edit');b.setHandoff({newDishName:'B handoff'});hold=false;release();await pause();let blocked=0;for(const action of [()=>a.setDraftPlan(id,saved,'import'),()=>a.clearDraftPlan(id),()=>a.undoDraftPlan(id),()=>a.setHandoff({newDishName:'late A'}),()=>a.takeHandoff()])try{action();}catch(e){if(e.code==='session_changed')blocked++;}check('old Source completion and handles cannot mutate B',blocked===5&&JSON.stringify(b.getDraftPlan(id))===JSON.stringify(expected)&&b.takeHandoff().newDishName==='B handoff',{blocked,plan:b.getDraftPlan(id)});});
await caseOf('handoff same and changed API',async()=>{await reset();const a=drafts;a.setHandoff({newIngredientName:'A handoff',returnTo:'#/admin/dish/soup'});let el=document.createElement('section');app.replaceChildren(el);await renderIngredient(el,{lang:'en',rest:'new',route:'admin',planId:id,data:{},t:x=>x},'new',api);check('Ingredient consumes same API handoff once',$('#adm-ing-name-zh')?.value==='A handoff'&&Object.keys(a.takeHandoff()).length===0);a.setHandoff({newIngredientName:'do not show B'});principal=2;el=document.createElement('section');app.replaceChildren(el);await renderIngredient(el,{lang:'uk',rest:'new',route:'admin',planId:id,data:{},t:x=>x},'new',api);check('Ingredient never consumes a prior identity handoff',$('#adm-ing-name-zh')?.value==='');await reset();const oldApi=api,oldKey=api.sessionKey(),oldHandle=bindDraftStore(api);oldHandle.setDraftPlan(id,saved,'import');oldHandle.setHandoff({newDishName:'previous API'});connect();await paint();check('equal session keys on different APIs do not share drafts',api!==oldApi&&api.sessionKey()===oldKey&&!app.querySelector('.adm-notice-action')&&drafts.getDraftPlan(id)===null&&Object.keys(drafts.takeHandoff()).length===0);});
out.textContent=JSON.stringify({summary:`${checks.filter(x=>x.pass).length}/${checks.length}`,checks,requests},null,2);(document.querySelector('#run')as HTMLButtonElement).disabled=false;}
document.querySelector('#run')!.addEventListener('click',()=>void run());
