import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm,readFile,readdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {tmpdir} from 'node:os';
import {dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {test,after} from 'node:test';
const here=dirname(fileURLToPath(import.meta.url)),req=createRequire(import.meta.url),vr=createRequire(req.resolve('vite/package.json')),esbuild=await import(pathToFileURL(vr.resolve('esbuild')));
const dir=await mkdtemp(join(tmpdir(),'shopping-copy-'));after(()=>rm(dir,{recursive:true,force:true}));
const built=await esbuild.build({stdin:{contents:`export {shoppingCopy} from './src/pages/shopping-copy';export {projectTeamMeals,estimateShoppingList,createShoppingList,applyShoppingDecision} from '../core/src/index';`,resolveDir:join(here,'..')},bundle:true,write:false,format:'esm',platform:'browser',loader:{'.css':'empty'},logLevel:'silent'});await writeFile(join(dir,'page.mjs'),built.outputFiles[0].text);const module=await import(pathToFileURL(join(dir,'page.mjs')));
const A='a'.repeat(40),list={id:'shop',basis:{sourceRevision:A,selection:[{menuPlanRef:'week',date:'2026-09-14',mealType:'lunch'}]},items:[{ingredientRef:'rice',decision:'buy',bought:true},{ingredientRef:'salt',decision:'check',previous:{decision:'buy',bought:true}},{ingredientRef:'oil',decision:'available'}]};
const projection={collection:{items:[],issues:[],coverage:{enumeration:'complete',references:'resolved',recipeCompleteness:'unverified'}},dishes:{},ingredients:{rice:{name:{zh:'米',en:'Rice',uk:'Рис'}},salt:{name:{zh:'盐',en:'Salt',uk:'Сіль'}},oil:{name:{zh:'油',en:'Oil',uk:'Олія'}}}};
test('copy explicitly includes all current decisions without promoting old bought references',()=>{assert.equal(typeof module.shoppingCopy,'function');const text=module.shoppingCopy(list,projection,'en',{items:[],budgetStatus:'not-applicable'});assert.match(text,/Rice.*Bought/);assert.match(text,/Salt.*Check/);assert.doesNotMatch(text,/Salt.*Bought/);assert.match(text,/Oil.*Available/);assert.match(text,/Current page/);assert.match(text,new RegExp(A));});
test('copy preserves raw unresolved reference and meal scope in each language',()=>{assert.equal(typeof module.shoppingCopy,'function');const input={...list,items:[{ingredientRef:'unknown',decision:'check'}]};for(const lang of ['zh','en','uk']){const text=module.shoppingCopy(input,projection,lang,{items:[],budgetStatus:'not-applicable'});assert.match(text,/unknown/);assert.match(text,/2026-09-14/);assert.doesNotMatch(text,/(?<![\d.])0 (?:g|kg)\b/);}});

// Explicit local variations of the approved A boundary data, projected/estimated by actual core.
const data=join(here,'../../../test/fixtures/contracts/valid/boundaries/data');
async function records(folder){return Object.fromEntries(await Promise.all((await readdir(join(data,folder))).filter(f=>f.endsWith('.json')).map(async f=>[f.slice(0,-5),JSON.parse(await readFile(join(data,folder,f),'utf8'))])));}
const seed={menuPlans:await records('menu-plans'),dishes:await records('dishes'),ingredients:await records('ingredients'),techniques:JSON.parse(await readFile(join(data,'techniques.json'),'utf8'))};
const freeze=x=>{if(x&&typeof x==='object'){Object.values(x).forEach(freeze);Object.freeze(x);}return x;};
function basis(input,selection){const selectionBasis={sourceRevision:A,selection};return {projection:module.projectTeamMeals(input,selectionBasis),estimate:module.estimateShoppingList(input,selection,'2026-09-14'),list:module.createShoppingList('export-shop',selectionBasis,input)};}
function varied(){const input=structuredClone(seed);delete input.menuPlans['team-week'].meals[0].plannedServings;delete input.dishes['second-dish'].components[0].qty;
 input.dishes['first-dish'].components.push({ingredientRef:'tomato',qty:{value:1,unit:'g'}},{ingredientRef:'missing-material',prep:{techniqueRef:'missing-cut'}});
 input.menuPlans['team-week'].meals.push({...input.menuPlans['team-week'].meals[0]},{date:'2026-09-15',mealType:'dinner',dishRef:'missing-recipe'});
 const selection=[{menuPlanRef:'team-week',date:'2026-09-14',mealType:'lunch'},{menuPlanRef:'team-week',date:'2026-09-15',mealType:'dinner'},{menuPlanRef:'team-week',date:'2026-09-16',mealType:'breakfast'}];
 const view=basis(input,selection);view.list=module.applyShoppingDecision(view.list,'salt','available');view.list=module.applyShoppingDecision(view.list,'cooking-oil','buy');view.list=module.applyShoppingDecision(view.list,'tomato-other','buy',true);return freeze(view);}
const labels={zh:{check:'待核对',buy:'待买',available:'已有',bought:'已买',tomato:'番茄',original:'原配方用量',planned:'计划份数',base:'配方基准份数',row:'计划行',component:'配料项',missingQty:'用量未录',taste:'适量',purchase:'采购规格未录',components:'尚未录入配料',dish:'菜谱未找到',empty:'所选餐次没有菜品记录',technique:'技法资料未找到',plan:'计划未找到',budget:'不代表完整预算'},en:{check:'Check',buy:'Buy',available:'Available',bought:'Bought',tomato:'Tomato',original:'Original recipe quantity',planned:'Planned servings',base:'Recipe servings',row:'Plan row',component:'Recipe item',missingQty:'Quantity not recorded',taste:'To taste',purchase:'Purchase specification missing',components:'Ingredients not recorded',dish:'Recipe missing',empty:'No dish recorded for this meal',technique:'Technique missing',plan:'Plan missing',budget:'not a complete budget'},uk:{check:'Перевірити',buy:'Купити',available:'Є в наявності',bought:'Куплено',tomato:'Помідор',original:'Початкова кількість рецепта',planned:'Порції в плані',base:'Порції рецепта',row:'Рядок плану',component:'Складник рецепта',missingQty:'Кількість не записано',taste:'За смаком',purchase:'Закупівельні параметри не записано',components:'Інгредієнти не записано',dish:'Рецепт не знайдено',empty:'Для цього прийому їжі страву не записано',technique:'Техніку не знайдено',plan:'План не знайдено',budget:'не повним бюджетом'}};
for(const lang of ['zh','en','uk']){
 const l=labels[lang];
 test(`${lang}: real core export groups four current decisions and distinguishes same-name IDs`,()=>{const view=varied(),out=module.shoppingCopy(view.list,view.projection,lang,view.estimate);for(const key of ['check','buy','available','bought'])assert.ok(out.includes(`\n\n${l[key]}\n`),key);assert.ok(out.includes(`${l.tomato} [tomato] — ${l.check}`));assert.ok(out.includes(`${l.tomato} [tomato-other] — ${l.bought}`));assert.ok(out.includes(A));assert.ok(out.includes('missing-material'));assert.ok(out.includes(l.budget));});
 test(`${lang}: every raw source occurrence retains original quantity, both serving fields and zero-index addresses`,()=>{const view=varied(),out=module.shoppingCopy(view.list,view.projection,lang,view.estimate);for(const item of view.projection.collection.items)for(const source of item.sources){const address=`${l.row}: ${source.mealIndex+1} · ${l.component}: ${source.componentIndex+1}`;const header=out.split('\n').findIndex(line=>line.includes(item.ingredientRef)&&line.includes(' — '));assert.ok(header>=0);const block=out.split('\n').slice(header+1);const end=block.findIndex(line=>!line.startsWith('  '));const sourceLines=block.slice(0,end<0?undefined:end).filter(line=>line.includes(`${l.original}:`));assert.equal(sourceLines.length,item.sources.length);assert.equal(sourceLines.filter(line=>line.includes(address)).length,1,address);}assert.ok(out.includes(`${l.original}: 300 g`));assert.ok(out.includes(`${l.original}: ${l.missingQty}`));assert.ok(out.includes(`${l.original}: ${l.taste}`));assert.ok(out.includes(`${l.planned}: 2`));assert.ok(out.includes(`${l.base}: 2`));assert.ok(out.includes('first-dish'));assert.ok(out.includes('second-dish'));assert.doesNotMatch(out,/(?<![\d.])0 (?:g|kg)\b/);});
 test(`${lang}: concrete collection issues and source-bound estimate reasons survive independently of candidate rows`,()=>{const view=varied(),out=module.shoppingCopy(view.list,view.projection,lang,view.estimate);for(const reason of [l.purchase,l.components,l.dish,l.empty,l.technique])assert.ok(out.includes(reason),reason);assert.ok(out.split('\n').some(line=>line.includes(l.components)&&line.includes('name-only')));assert.ok(out.split('\n').some(line=>line.includes(l.technique)&&line.includes('missing-cut')&&line.includes('missing-material')));assert.ok(out.split('\n').some(line=>line.includes(l.purchase)&&line.includes('salt')));assert.ok(out.split('\n').some(line=>line.includes('second-dish')&&line.includes(`${l.row}: 2`)&&line.includes(l.base)));assert.doesNotMatch(out,/components-unrecorded|missing-plan|empty-selection|missing-technique/);});
 test(`${lang}: empty candidate collections still export localized missing-plan and empty-selection addresses`,()=>{const selection=[{menuPlanRef:'absent-plan',date:'2026-09-18',mealType:'dinner'},{menuPlanRef:'team-week',date:'2026-09-17',mealType:'breakfast'}],p=module.projectTeamMeals(seed,{sourceRevision:A,selection}),e=module.estimateShoppingList(seed,selection,'2026-09-14'),empty={shoppingListVersion:'1',id:'unresolved',basis:{sourceRevision:A,selection},items:[]};assert.equal(p.collection.items.length,0);const out=module.shoppingCopy(empty,freeze(p),lang,freeze(e));assert.ok(out.includes(l.plan));assert.ok(out.split('\n').some(line=>line.includes(l.plan)&&line.includes('absent-plan')));assert.ok(out.split('\n').some(line=>line.includes(l.empty)&&line.includes('2026-09-17')));});
}
test('complete core estimate with no purchase lines keeps the current check decision and does not invent a total',()=>{const input=structuredClone(seed);input.menuPlans['team-week'].meals=input.menuPlans['team-week'].meals.slice(0,1);input.dishes['first-dish'].components=input.dishes['first-dish'].components.slice(0,1);Object.assign(input.ingredients.tomato,{trackStock:true,onHand:100000});const view=freeze(basis(input,[{menuPlanRef:'team-week',date:'2026-09-14',mealType:'lunch'}]));assert.equal(view.estimate.items[0].status,'complete');assert.equal(view.estimate.items[0].lines.length,0);const out=module.shoppingCopy(view.list,view.projection,'en',view.estimate);assert.match(out,/Tomato \[tomato\] — Check/);assert.doesNotMatch(out,/Tomato.*Available|Total|(?<![\d.])0 (?:CNY|g)\b/);});

test('complete references come directly from the supplied core estimate, with no sum or mutation',()=>{const input=structuredClone(seed);input.menuPlans['team-week'].meals=input.menuPlans['team-week'].meals.slice(0,1);input.dishes['first-dish'].components=input.dishes['first-dish'].components.slice(0,1);const view=freeze(basis(input,[{menuPlanRef:'team-week',date:'2026-09-14',mealType:'lunch'}]));assert.equal(view.estimate.items[0].status,'complete');assert.ok(view.estimate.items[0].lines.length);const before=JSON.stringify(view),out=module.shoppingCopy(view.list,view.projection,'en',view.estimate);for(const {supplier,line} of view.estimate.items[0].lines){assert.ok(out.includes(`Calculated reference: ${supplier}`));assert.ok(out.includes(`${line.packs} × ${line.trace.packSize} ${line.trace.packUnit}`));if(line.amount)assert.ok(out.includes(`${line.amount.amount} ${line.amount.currency}`));}assert.equal(JSON.stringify(view),before);assert.match(out,/not a complete budget/);assert.doesNotMatch(out,/Total/);});
