/** Explicit routes only: the gateway is not a general-purpose HTTP proxy. */
export const KNOWLEDGE_JSON_MAX_BYTES = 4 * 1024 * 1024;
export const KNOWLEDGE_UPLOAD_MAX_BYTES = 8 * 1024 * 1024 + 64 * 1024;

export const KNOWLEDGE_ROUTES = [
  ["GET", "/knowledge/health"],
  ["GET", "/knowledge/recipes"],
  ["GET", "/knowledge/recipes/:id"],
  ["GET", "/knowledge/recipes/:id/source-illustrations"],
  ["GET", "/knowledge/recipes/:id/revisions"],
  ["GET", "/knowledge/recipes/:id/revisions/:version"],
  ["POST", "/knowledge/recipes"],
  ["PUT", "/knowledge/recipes/:id"],
  ["POST", "/knowledge/recipes/:id/archive"],
  ["POST", "/knowledge/sources"],
  ["POST", "/knowledge/assets/external"],
  ["POST", "/knowledge/assets/upload"],
  ["POST", "/knowledge/assets/:id/rights"],
  ["GET", "/knowledge/assets/:id/content"],
  ["GET", "/knowledge/ingredients"],
  ["GET", "/knowledge/techniques"],
  ["GET", "/knowledge/recipes/:id/legacy"],
  ["POST", "/knowledge/favorites/import/prepare"],
  ["POST", "/knowledge/favorites/import/apply"],
  ["GET", "/knowledge/favorites/imports"],
  ["GET", "/knowledge/favorites/imports/:id"],
  ["GET", "/knowledge/favorites/items"],
  ["GET", "/knowledge/favorites/items/:id"],
  ["GET", "/knowledge/favorites/items/:id/captures"],
  ["POST", "/knowledge/favorites/items/:id/captures"],
  ["GET", "/knowledge/favorites/items/:id/candidates"],
  ["POST", "/knowledge/favorites/items/:id/candidates"],
  ["GET", "/knowledge/favorites/candidates/:id"],
  ["POST", "/knowledge/favorites/candidates/:id/review"],
  ["POST", "/knowledge/favorites/candidates/:id/illustrations"],
  ["POST", "/knowledge/favorites/items/:id/classify"],
] as const;
