import assert from 'node:assert/strict';
import {test} from 'node:test';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createWorkflowPublicationFixture} from '../../packages/web/test/e2e/team-meals/workflow-publication-fixture.mjs';
import {WORKER,call,bearer} from '../../packages/worker/test/helpers.mjs';
const worker=(await import(WORKER)).default;
const productionRevision='25f601a44e0f15c57d8456419c6706e2ef2ced89';
test('durable fixture restores private saves separately from the last published bytes and interrupted runs',async t=>{
 const storageRoot=await mkdtemp(join(tmpdir(),'canteen-persistence-test-'));
 t.after(()=>rm(storageRoot,{recursive:true,force:true}));
 const options={productionRevision,siteUrl:'http://127.0.0.1:4280/canteen/',storageRoot};
 let f=await createWorkflowPublicationFixture(options);
 const request=(method,path,opts={})=>call(worker,f.env,method,path,{...opts,headers:{...bearer('chef'),...opts.headers}});
 const publicBefore=await readFile(join(f.active.dist,'data/team-meals/team-week.json'));
 const initial=f.active.commit;
 const plan=(await request('GET','/source/plan/team-week')).body;
 plan.content.meals.push({date:'2026-09-13',mealType:'lunch',dishRef:'tomato-egg-stir-fry'});
 const saved=await request('POST','/plan/team-week',{body:plan.content,headers:{'If-Match':plan.blobSha}});
 assert.equal(saved.status,200);
 assert.equal(typeof f.saveState,'function','persistent mode must expose a durable checkpoint');
 await f.saveState();
 f=await createWorkflowPublicationFixture(options);
 assert.equal(f.repo.head,saved.body.commit);
 assert.equal(f.active.commit,initial,'restart must not publish private saves');
 assert.deepEqual(await readFile(join(f.active.dist,'data/team-meals/team-week.json')),publicBefore);
 assert.deepEqual((await request('GET','/source/plan/team-week')).body.content,plan.content);
 const pending=await request('POST','/publish');assert.equal(pending.status,200);await f.saveState();
 // Crash after artifact generation, before checkpoint activation.
 assert.equal((await f.complete(pending.body.runId)).state,'success');
 f=await createWorkflowPublicationFixture(options);
 const interrupted=await request('GET',`/publish/${pending.body.runId}`);
 assert.equal(interrupted.body.runConclusion,'failure');assert.equal(f.active.commit,initial);
 const publish=await request('POST','/publish');assert.equal(publish.status,200);assert.notEqual(publish.body.runId,pending.body.runId);
 // Save B while publication A is queued; A must use its captured commit.
 const b=(await request('GET','/source/plan/team-week')).body;b.content.name.zh+=' · private B';
 const saveB=await request('POST','/plan/team-week',{body:b.content,headers:{'If-Match':b.blobSha}});assert.equal(saveB.status,200);await f.saveState();
 assert.equal((await f.complete(publish.body.runId)).state,'success');await f.saveState();
 f=await createWorkflowPublicationFixture(options);
 assert.equal(f.active.commit,saved.body.commit);
 assert.equal((await request('GET',`/publish/${publish.body.runId}`)).body.status,'success');
 const published=JSON.parse(await readFile(join(f.active.dist,'data/team-meals/team-week.json')));
 assert.deepEqual(published.menuPlans['team-week'],plan.content);
 // A failed formal build must keep the previous publication through restart.
 const latest=(await request('GET','/source/plan/team-week')).body;
 latest.content.meals[0].dishRef='missing-recipe';
 assert.equal((await request('POST','/plan/team-week',{body:latest.content,headers:{'If-Match':latest.blobSha}})).status,200);
 const broken=await request('POST','/publish');await f.saveState();assert.equal((await f.complete(broken.body.runId)).state,'failure');await f.saveState();
 f=await createWorkflowPublicationFixture(options);
 assert.equal(f.active.commit,saved.body.commit);
 assert.notEqual(f.repo.head,f.active.commit);
 assert.equal((await request('GET',`/publish/${broken.body.runId}`)).body.runConclusion,'failure');
 await assert.rejects(f.env.__fetch('https://outside.invalid/test'),/only modeled/);
 const checkpoint=await readFile(join(storageRoot,'checkpoint.json'));
 await writeFile(join(storageRoot,'checkpoint.json'),'{broken');
 await assert.rejects(createWorkflowPublicationFixture(options),SyntaxError);
 await writeFile(join(storageRoot,'checkpoint.json'),checkpoint);
 const manifest=join(f.active.dist,'data/build.json');const manifestBytes=await readFile(manifest);
 await writeFile(manifest,'{}');await assert.rejects(createWorkflowPublicationFixture(options));
 assert.deepEqual(await readFile(join(storageRoot,'checkpoint.json')),checkpoint,'corruption must not reseed');
 await writeFile(manifest,manifestBytes);
});
