import assert from 'node:assert/strict';
import {test} from 'node:test';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {mkdtemp,rm,writeFile,readFile,rename,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {PNG_A} from '../../packages/worker/test/image-fixtures.mjs';
const server=new URL('./server.mjs',import.meta.url);
const port=Number(process.env.CANTEEN_SERVICE_TEST_PORT??4281),origin=`http://127.0.0.1:${port}`;
async function until(check){for(let i=0;i<300;i++){const r=await check();if(r)return r;await new Promise(r=>setTimeout(r,100));}throw new Error('Service condition timed out');}
test('HTTP auth, raw image metadata, conditional writes, SIGKILL restore, publication and checkpoint failure',async t=>{
 const root=await mkdtemp(join(tmpdir(),'canteen-service-test-')),storageRoot=join(root,'state'),configPath=join(root,'runtime.json');
 const tokens=Object.fromEntries(['chef','buyer','admin'].map(r=>[r,randomBytes(32).toString('base64url')]));
 await writeFile(configPath,JSON.stringify({port,storageRoot,tokens,productionRevision:'25f601a44e0f15c57d8456419c6706e2ef2ced89'}),{mode:0o600});
 let child,logs='';
 const launch=()=>{const c=spawn(process.execPath,[server.pathname],{env:{...process.env,CANTEEN_TEST_CONFIG:configPath},stdio:['ignore','pipe','pipe']});c.stdout.on('data',d=>logs+=d);c.stderr.on('data',d=>logs+=d);return c;};
 const stop=async signal=>{const c=child;if(!c||c.exitCode!==null||c.signalCode!==null)return;const ended=once(c,'exit');c.kill(signal);await ended;};
 t.after(async()=>{await stop('SIGKILL');await rm(root,{recursive:true,force:true});});
 const ready=async()=>until(async()=>{if(child.exitCode!==null)throw new Error(logs);try{const r=await fetch(origin+'/_test/status');return r.ok?await r.json():false;}catch{return false;}});
 const call=async(method,path,{body,headers={}}={})=>{const r=await fetch(origin+'/__q/worker'+path,{method,headers:{Authorization:`Bearer ${tokens.chef}`,...headers},body});const bytes=Buffer.from(await r.arrayBuffer());return {status:r.status,headers:r.headers,bytes,body:r.headers.get('content-type')?.includes('json')?JSON.parse(bytes):null};};
 child=launch();const initial=await ready();
 const publicBefore=await (await fetch(origin+'/canteen/data/team-meals/team-week.json')).text();
 assert.equal((await fetch(origin+'/__q/worker/source/plan/team-week')).status,401);
 assert.equal((await fetch(origin+'/__q/worker/source/plan/team-week',{headers:{Authorization:'Bearer chef'+'A'.repeat(39)}})).status,401);
 assert.equal((await fetch(origin+'/_test/status',{headers:{Origin:'https://outside.invalid'}})).status,403);
 for(const route of ['/__q/evidence','/__q/control','/__q/diagnostics'])assert.equal((await fetch(origin+route)).status,404);
 const duplicate=launch();assert.notEqual((await once(duplicate,'exit'))[0],0,'second instance must fail without touching state');
 const upload=await call('POST','/image/dishes/tomato-egg-stir-fry',{body:PNG_A,headers:{'Content-Type':'image/png','X-Image-License':'CC0','X-Image-Name':'test-pixel','X-Image-Author':'Test fixture','X-Image-Source-Url':'https://example.invalid/test-pixel'}});
 assert.equal(upload.status,200,JSON.stringify(upload.body));assert.equal(upload.body.image.license,'CC0');assert.equal(upload.body.image.author,'Test fixture');
 const dish=(await call('GET','/source/dish/tomato-egg-stir-fry')).body;
 dish.content.image=upload.body.image;dish.content.description.zh+=' 测试像素，并非食物照片。';
 assert.equal((await call('POST','/dish/tomato-egg-stir-fry/draft',{body:JSON.stringify(dish.content),headers:{'Content-Type':'application/json','If-Match':dish.blobSha}})).status,200);
 const plan=(await call('GET','/source/plan/team-week')).body;
 plan.content.name.zh+=' · HTTP persistence demo';
 const opts={body:JSON.stringify(plan.content),headers:{'Content-Type':'application/json','If-Match':plan.blobSha}};
 const saved=await call('POST','/plan/team-week',opts);assert.equal(saved.status,200);
 const beforeKill=(await call('GET','/source/plan/team-week')).body;
 await stop('SIGKILL');child=launch();const restarted=await ready();assert.notEqual(restarted.bootId,initial.bootId);
 assert.equal(restarted.privateHead,saved.body.commit);assert.equal(restarted.publicHead,initial.publicHead);
 assert.equal(await (await fetch(origin+'/canteen/data/team-meals/team-week.json')).text(),publicBefore);
 assert.deepEqual((await call('GET','/source/plan/team-week')).body,beforeKill);
 const old=(await call('GET',`/source/plan/team-week?revision=${plan.commit}`));assert.equal(old.status,200);assert.equal(old.body.commit,plan.commit);
 assert.equal((await call('POST','/plan/team-week',opts)).status,409,'stale If-Match remains a conflict after restart');
 const retried=await call('POST','/plan/team-week',{...opts,headers:{...opts.headers,'If-Match':beforeKill.blobSha}});
 assert.equal(retried.status,200);assert.equal(retried.body.unchanged,true);assert.equal(retried.body.commit,saved.body.commit);
 assert.equal((await call('GET','/source/plan/team-week')).body.commit,saved.body.commit);
 const asset=await call('GET','/asset?owner=data%2Fdishes%2Ftomato-egg-stir-fry.json&pointer=%2Fimage');
 assert.equal(asset.status,200,JSON.stringify(asset.body));assert.deepEqual(asset.bytes,PNG_A);
 const published=await call('POST','/publish');assert.equal(published.status,200);
 await until(async()=>{const r=await call('GET',`/publish/${published.body.runId}`);if(r.body.runConclusion==='failure')throw new Error(JSON.stringify(r.body));return r.body.status==='success';});
 await stop('SIGKILL');child=launch();const afterPublish=await ready();assert.equal(afterPublish.publicHead,saved.body.commit);
 // Simulate a filesystem failure at the sole checkpoint commit point.
 const checkpoint=join(storageRoot,'checkpoint.json'),backup=join(root,'checkpoint-backup.json');
 await rename(checkpoint,backup);await mkdir(checkpoint);
 const p=(await call('GET','/source/plan/team-week')).body;p.content.name.zh+=' unacknowledged';
 const ended=once(child,'exit');
 await assert.rejects(call('POST','/plan/team-week',{body:JSON.stringify(p.content),headers:{'Content-Type':'application/json','If-Match':p.blobSha}}));
 assert.equal((await ended)[0],1,'checkpoint I/O failure must stop service, without success ACK');
 await rm(checkpoint,{recursive:true});await rename(backup,checkpoint);
 child=launch();const recovered=await ready();assert.equal(recovered.privateHead,saved.body.commit);assert.equal(recovered.publicHead,saved.body.commit);
 assert.deepEqual((await call('GET','/source/plan/team-week')).body,beforeKill);
 t.diagnostic(JSON.stringify({initial:initial.bootId,restarted:restarted.bootId,published:saved.body.commit,imageBytes:asset.bytes.length,checkpointFailure:'no ACK; canonical checkpoint restored'}));
});
